import { createContext, useCallback, useContext, useEffect, useMemo, useState } from 'react';

const STORAGE_KEY = 'ximor_language';
const DEFAULT_LANGUAGE = 'uz';

export const LANGUAGES = [
  { code: 'uz', short: 'UZ', name: "O'zbekcha" },
  { code: 'ru', short: 'RU', name: 'Русский' },
  { code: 'en', short: 'EN', name: 'English' },
];

const translations = {
  uz: {
    common: {
      back: 'Orqaga',
      close: 'Yopish',
      loading: 'Yuklanmoqda…',
      retry: "Qayta urinib ko'ring",
      save: 'Saqlash',
      saved: 'Saqlangan',
      send: 'Yuborish',
      open: 'Ochiq',
      solved: 'Yechilgan',
      copied: 'Nusxalandi',
      optional: 'ixtiyoriy',
      now: 'Hozir',
      today: 'Bugun',
      yesterday: 'Kecha',
      language: 'Til',
    },
    time: {
      now: 'Hozir',
      minutesAgo: '{{count}} daq oldin',
      hoursAgo: '{{count}} soat oldin',
      daysAgo: '{{count}} kun oldin',
    },
    nav: {
      main: "Asosiy bo'limlar",
      chat: 'Chat',
      olympiads: 'Olimpiadalar',
      community: 'Hamjamiyat',
      ranking: 'Reyting',
      tools: 'Asboblar',
      news: 'Yangiliklar',
      profile: 'Profil',
      myProfile: 'Profilim',
      login: 'Kirish',
      logout: 'Chiqish',
      adminPanel: 'Admin Panel',
      moderatorPanel: 'Moderator Panel',
      mobile: 'Mobil navigatsiya',
    },
    header: {
      tagline: 'Beyond Curriculum · Kimyo',
      search: 'Savol, teg yoki reaksiya qidiring',
      theme: 'Mavzuni almashtirish',
      notifications: 'Bildirishnomalar',
      allRead: "hammasi o'qilgan",
      newCount: '{{count}} yangi',
      noNotifications: "Hali bildirishnoma yo'q",
      askQuestion: 'Savol berish',
    },
    auth: {
      welcome: 'Xush kelibsiz',
      createAccount: 'Hisob yaratish',
      login: 'Kirish',
      register: "Ro'yxatdan o'tish",
      fullName: "To'liq ism",
      username: 'Username',
      password: 'Parol',
      minPassword: 'kamida 6 ta belgi',
      noAccount: "Hisob yo'qmi?",
      haveAccount: 'Hisob bormi?',
      registerAction: "Ro'yxatdan o'ting",
      loginAction: 'Kiring',
      registerError: "Ro'yxatdan o'tishda xato",
      loginError: 'Kirish xatosi',
    },
    forum: {
      categories: "Bo'limlar",
      all: 'Hammasi',
      organic: 'Organik kimyo',
      inorganic: 'Anorganik',
      physical: 'Fizikaviy',
      analytical: 'Analitik',
      recent: "So'nggi",
      hot: 'Qaynoq',
      unanswered: 'Javobsiz',
      saved: 'Saqlangan',
      feed: 'Savollar oqimi',
      compact: 'Ixcham',
      spacious: 'Keng',
      masteryLevel: 'Mastery darajasi',
      upvotes: 'Ovozlar',
      answers: 'Javoblar',
      shared: 'Ulashdi',
      dailySprint: 'Kunlik sprint',
      sprintText: 'Bugun uchta kimyo muhokamasida foydali izoh qoldiring.',
      trendingTags: 'Ommabop teglar',
      demoMode: 'Demo rejim',
      demoText: "Live API sekin javob bermoqda, shuning uchun namunaviy savollar ko'rsatilmoqda.",
      noResults: 'Natija topilmadi',
      noResultsHint: "Boshqa so'z yoki fan bilan qidirib ko'ring.",
      pinned: 'Mahkamlangan mavzu',
      views: "Ko'rishlar",
      copyLink: 'Savol havolasini nusxalash',
      linkCopied: 'Havola nusxalandi',
      upvote: 'Yuqoriga ovoz berish',
      downvote: 'Pastga ovoz berish',
      voteUp: 'Yuqoriga ovoz',
      voteDown: 'Pastga ovoz',
      voteRemoved: 'Ovoz olib tashlandi',
      voteSaved: 'Ovoz saqlandi',
      voteFailed: "Ovoz saqlanmadi. Qayta urinib ko'ring",
      demoVote: 'Demo rejimda ovozlar saqlanmaydi',
      savedUpdated: 'Saqlanganlar yangilandi',
      answerSent: 'Javob yuborildi',
      topicCreated: 'Mavzu yaratildi',
      topicCreateError: "Mavzu yaratishda xato. Qayta urinib ko'ring.",
      follow: 'Kuzatish',
      discussion: 'Muhokama',
      usefulFirst: 'Eng foydalilari yuqorida',
      answerCount: '{{count}} ta javob',
      noAnswers: "Hali javob yo'q",
      noAnswersHint: 'Birinchi aniq javob shu muhokamani boshlab beradi.',
      writeAnswer: 'Javob yozish',
      answerPlaceholder: "Qisqa ishora, formula yoki to'liq yechim yozing…",
      sendAnswer: 'Javob yuborish',
      sending: 'Yuborilmoqda…',
    },
    composer: {
      newTopic: 'Yangi mavzu',
      newQuestion: 'Yangi kimyo savoli',
      write: 'Yozish',
      preview: "Ko'rib chiqish",
      title: 'Sarlavha',
      titlePlaceholder: 'Masalan: sulfat kislotaning CuO bilan reaksiyasi qanday boradi?',
      chemistry: 'Kimyo',
      formula: 'Formula',
      fraction: 'Kasr',
      reaction: 'Reaksiya',
      reversible: 'Qaytar',
      charge: 'Zaryad',
      state: 'Holat',
      precipitate: "Cho'kma",
      formatting: 'Markdown formatlash',
      bold: 'Qalin',
      italic: 'Kursiv',
      list: "Ro'yxat",
      quote: 'Iqtibos',
      code: 'Kod',
      link: 'Havola',
      questionText: 'Savol matni',
      questionPlaceholder: "Savolingizni yozing — formulalarni to'g'ridan-to'g'ri qo'shing.",
      category: "Bo'lim",
      tags: 'Teglar',
      tagsHint: 'vergul bilan ajrating',
      emptyPreview: "Savol matni yozilganda bu yerda ko'rinadi.",
      emptyTitle: 'Sarlavha hali yozilmagan',
      previewLabel: "Ko'rinishi",
      image: 'Rasm',
      removeImage: '{{name}} rasmini olib tashlash',
      cancel: 'Bekor qilish',
      creating: 'Saqlanmoqda…',
      create: 'Mavzu yaratish',
    },
    question: {
      forum: 'Forum',
      notFound: 'Savol topilmadi',
      asked: "So'radi",
      activity: 'Faollik',
      status: 'Holat',
      about: 'Savol haqida',
      tags: 'Teglar',
      acceptAnswer: 'Bu javobni qabul qilish',
      accepted: 'Qabul qilindi',
      answerAccepted: 'Javob qabul qilindi',
      markSolved: 'Yechildi',
      markOpen: 'Ochiq qilish',
      signInToAnswer: 'Javob berish uchun tizimga kiring',
      loginOrRegister: "Kirish / Ro'yxatdan o'tish",
      helpful: 'Foydali',
      unhelpful: 'Foydasiz',
      correct: "To'g'ri",
      incorrect: "Noto'g'ri",
      delete: "O'chirish",
      answerDeleted: "Javob o'chirildi",
      answerMarked: 'Javob belgilandi',
      questionSolved: 'Savol yechildi',
      questionOpened: 'Savol ochiq qilindi',
      questionLinkCopied: 'Savol havolasi nusxalandi',
      answerLinkCopied: 'Javob havolasi nusxalandi',
      copyAnswerLink: 'Javob havolasini nusxalash',
      copyFailed: "Havolani nusxalab bo'lmadi",
      genericError: 'Xato yuz berdi',
      firstAnswer: 'Birinchi javobni yozing!',
      confirmDelete: "Bu javobni o'chirasizmi?",
    },
    insights: {
      liveRoom: 'Jonli xona',
      connections: '{{count}} ulanish',
      topMentors: 'Eng faol foydalanuvchilar',
      community: 'Hamjamiyat',
      topUsers: 'Eng faol foydalanuvchilar',
      activeUser: 'Faol ishtirokchi',
      userBadges: ['Eng faol javobchi', "Ko'p yordam bergan", 'Foydali yechimlar', 'Muhokamada faol', 'Haftaning ishtirokchisi'],
      weeklyChallenge: 'Hafta chaqiruvi',
      reactionMarathon: 'Reaksiya marafoni',
      challengeText: "Har kuni bitta kimyo reaksiyasini to'liq mexanizm bilan yozing va community bilan muhokama qiling.",
      view: "Ko'rish",
    },
    home: {
      chemistryChat: 'Kimyo chat',
      home: 'Bosh sahifa',
      features: 'Imkoniyatlar',
      about: 'Biz haqimizda',
      community: 'Hamjamiyat',
      eyebrow: 'Beyond curriculum · jonli kimyo yordami',
      title1: 'Eng jonli',
      title2: 'kimyo chat',
      title3: 'uchun yangi start',
      intro: "Ximor — savollar, mentor javoblari, formulalar va hamjamiyat energiyasi bitta joyda. Hozir asosiy sahna chat, keyin darslar va mashq bo'limlari ham qo'shiladi.",
      openChat: 'Chatni ochish',
      questionFlow: 'Savol oqimi',
      chemistrySections: "Kimyo bo'limi",
      lessonsMode: 'Darslar rejimi',
      mentorAnswered: 'Mentor javob berdi',
      newDiscussions: '{{count}} yangi muhokama',
      writeQuestion: 'Savol yozish…',
      featuresHeading: "Chat hozir ishlaydi, keyingi bo'limlar uchun joy allaqachon tayyor.",
      aboutHeading: 'Ximor — kimyoni birga tushunadigan hamjamiyat.',
      aboutText: "Maqsad oddiy: quruq javob emas, tushunarli yo'l. Har bir savol formulasi, urinishlari va muhokamasi bilan saqlanadi, shunda yangi o'quvchi ham undan foyda oladi.",
      roadmap: 'Ximor rivojlanish rejasi',
      now: 'Hozir',
      next: 'Keyin',
      nowItems: 'Chat, savollar, javoblar, reyting',
      nextItems: 'Darslar, mashqlar, mini olimpiadalar',
      later: 'Keyinroq',
      laterItems: 'Mentor xonalari, guruhlar, rivojlanish xaritasi',
      join: "Hamjamiyatga qo'shiling",
      joinText: "Savolingizni bering, yechim yozing va kimyoni birga tushuning.",
      communityHeading: "Birinchi muhokamani oching. Qolgan harakat ichkarida davom etadi.",
      communityChat: 'Hamjamiyat chati',
      communitySections: "Hamjamiyat bo'limlari",
      communityItems: ['Organik kimyo', 'DTM tayyorgarlik', 'Olimpiada sprinti', 'Reaksiya mexanizmlari', 'Analitik masalalar', 'Mentor javoblari'],
      reactionSearch: 'H2SO4 + CuO reaksiyasi…',
      grignardQuestion: 'Grignard mexanizmi qanday ishlaydi?',
      mentorMessage: "Karbonil uglerodiga nukleofil hujum bo'ladi.",
      learnerMessage: "Demak birlamchi spirt hosil bo'ladimi?",
      pressureQuestion: 'Le Chatelier: bosim oshsa?',
      feature1Title: "Chat birinchi o'rinda",
      feature1Text: "Savol, yechim, formula va rasm bitta jonli oqimda.",
      feature2Title: 'Kimyo formulalari tayyor',
      feature2Text: "Reaksiya, LaTeX, indeks va bosqichma-bosqich yechimlar chiroyli ko'rinadi.",
      feature3Title: 'Mentorlar va reyting',
      feature3Text: "Foydali javoblar yuqoriga ko'tariladi, faol yordamchilar esa hamjamiyatda ko'rinadi.",
      feature4Title: 'Darslar uchun joy bor',
      feature4Text: "Olimpiada, mini-kurs, test va mashq rejimlari uchun tuzilma tayyor.",
    },
  },
  ru: {
    common: {
      back: 'Назад',
      close: 'Закрыть',
      loading: 'Загрузка…',
      retry: 'Попробовать снова',
      save: 'Сохранить',
      saved: 'Сохранено',
      send: 'Отправить',
      open: 'Открыт',
      solved: 'Решён',
      copied: 'Скопировано',
      optional: 'необязательно',
      now: 'Сейчас',
      today: 'Сегодня',
      yesterday: 'Вчера',
      language: 'Язык',
    },
    time: {
      now: 'Сейчас',
      minutesAgo: '{{count}} мин назад',
      hoursAgo: '{{count}} ч назад',
      daysAgo: '{{count}} дн назад',
    },
    nav: {
      main: 'Основные разделы',
      chat: 'Чат',
      olympiads: 'Олимпиады',
      community: 'Сообщество',
      ranking: 'Рейтинг',
      tools: 'Инструменты',
      news: 'Новости',
      profile: 'Профиль',
      myProfile: 'Мой профиль',
      login: 'Войти',
      logout: 'Выйти',
      adminPanel: 'Панель администратора',
      moderatorPanel: 'Панель модератора',
      mobile: 'Мобильная навигация',
    },
    header: {
      tagline: 'Beyond Curriculum · Химия',
      search: 'Поиск вопроса, тега или реакции',
      theme: 'Сменить тему',
      notifications: 'Уведомления',
      allRead: 'всё прочитано',
      newCount: '{{count}} новых',
      noNotifications: 'Уведомлений пока нет',
      askQuestion: 'Задать вопрос',
    },
    auth: {
      welcome: 'Добро пожаловать',
      createAccount: 'Создать аккаунт',
      login: 'Войти',
      register: 'Регистрация',
      fullName: 'Полное имя',
      username: 'Имя пользователя',
      password: 'Пароль',
      minPassword: 'минимум 6 символов',
      noAccount: 'Нет аккаунта?',
      haveAccount: 'Уже есть аккаунт?',
      registerAction: 'Зарегистрируйтесь',
      loginAction: 'Войдите',
      registerError: 'Ошибка регистрации',
      loginError: 'Ошибка входа',
    },
    forum: {
      categories: 'Разделы',
      all: 'Все',
      organic: 'Органическая химия',
      inorganic: 'Неорганическая',
      physical: 'Физическая',
      analytical: 'Аналитическая',
      recent: 'Новые',
      hot: 'Популярные',
      unanswered: 'Без ответа',
      saved: 'Сохранённые',
      feed: 'Лента вопросов',
      compact: 'Компактно',
      spacious: 'Просторно',
      masteryLevel: 'Уровень мастерства',
      upvotes: 'Голоса',
      answers: 'Ответы',
      shared: 'Поделился',
      dailySprint: 'Ежедневный спринт',
      sprintText: 'Оставьте сегодня полезный комментарий в трёх обсуждениях по химии.',
      trendingTags: 'Популярные теги',
      demoMode: 'Демо-режим',
      demoText: 'Live API отвечает медленно, поэтому показаны демонстрационные вопросы.',
      noResults: 'Ничего не найдено',
      noResultsHint: 'Попробуйте другое слово или раздел.',
      pinned: 'Закреплённая тема',
      views: 'Просмотры',
      copyLink: 'Скопировать ссылку на вопрос',
      linkCopied: 'Ссылка скопирована',
      upvote: 'Проголосовать за',
      downvote: 'Проголосовать против',
      voteUp: 'Голос за',
      voteDown: 'Голос против',
      voteRemoved: 'Голос отменён',
      voteSaved: 'Голос сохранён',
      voteFailed: 'Не удалось сохранить голос. Попробуйте снова',
      demoVote: 'В демо-режиме голоса не сохраняются',
      savedUpdated: 'Сохранённые обновлены',
      answerSent: 'Ответ отправлен',
      topicCreated: 'Тема создана',
      topicCreateError: 'Не удалось создать тему. Попробуйте снова.',
      follow: 'Следить',
      discussion: 'Обсуждение',
      usefulFirst: 'Сначала самые полезные',
      answerCount: '{{count}} ответов',
      noAnswers: 'Ответов пока нет',
      noAnswersHint: 'Первый точный ответ начнёт это обсуждение.',
      writeAnswer: 'Написать ответ',
      answerPlaceholder: 'Напишите подсказку, формулу или полное решение…',
      sendAnswer: 'Отправить ответ',
      sending: 'Отправка…',
    },
    composer: {
      newTopic: 'Новая тема',
      newQuestion: 'Новый вопрос по химии',
      write: 'Написать',
      preview: 'Предпросмотр',
      title: 'Заголовок',
      titlePlaceholder: 'Например: как реагирует серная кислота с CuO?',
      chemistry: 'Химия',
      formula: 'Формула',
      fraction: 'Дробь',
      reaction: 'Реакция',
      reversible: 'Обратимая',
      charge: 'Заряд',
      state: 'Состояние',
      precipitate: 'Осадок',
      formatting: 'Форматирование Markdown',
      bold: 'Жирный',
      italic: 'Курсив',
      list: 'Список',
      quote: 'Цитата',
      code: 'Код',
      link: 'Ссылка',
      questionText: 'Текст вопроса',
      questionPlaceholder: 'Напишите вопрос — формулы можно вставлять прямо в текст.',
      category: 'Раздел',
      tags: 'Теги',
      tagsHint: 'разделяйте запятыми',
      emptyPreview: 'Здесь появится предварительный просмотр вопроса.',
      emptyTitle: 'Заголовок ещё не написан',
      previewLabel: 'Предпросмотр',
      image: 'Изображение',
      removeImage: 'Удалить изображение {{name}}',
      cancel: 'Отмена',
      creating: 'Сохранение…',
      create: 'Создать тему',
    },
    question: {
      forum: 'Форум',
      notFound: 'Вопрос не найден',
      asked: 'Автор',
      activity: 'Активность',
      status: 'Статус',
      about: 'О вопросе',
      tags: 'Теги',
      acceptAnswer: 'Принять этот ответ',
      accepted: 'Принят',
      answerAccepted: 'Ответ принят',
      markSolved: 'Решён',
      markOpen: 'Сделать открытым',
      signInToAnswer: 'Войдите, чтобы ответить',
      loginOrRegister: 'Войти / Регистрация',
      helpful: 'Полезный',
      unhelpful: 'Бесполезный',
      correct: 'Верный',
      incorrect: 'Неверный',
      delete: 'Удалить',
      answerDeleted: 'Ответ удалён',
      answerMarked: 'Ответ отмечен',
      questionSolved: 'Вопрос решён',
      questionOpened: 'Вопрос снова открыт',
      questionLinkCopied: 'Ссылка на вопрос скопирована',
      answerLinkCopied: 'Ссылка на ответ скопирована',
      copyAnswerLink: 'Скопировать ссылку на ответ',
      copyFailed: 'Не удалось скопировать ссылку',
      genericError: 'Произошла ошибка',
      firstAnswer: 'Напишите первый ответ!',
      confirmDelete: 'Удалить этот ответ?',
    },
    insights: {
      liveRoom: 'Сейчас онлайн',
      connections: '{{count}} подключений',
      topMentors: 'Самые активные участники',
      community: 'Сообщество',
      topUsers: 'Самые активные участники',
      activeUser: 'Активный участник',
      userBadges: ['Самый активный автор ответов', 'Много помогал другим', 'Полезные решения', 'Активен в обсуждениях', 'Участник недели'],
      weeklyChallenge: 'Задание недели',
      reactionMarathon: 'Марафон реакций',
      challengeText: 'Каждый день записывайте одну реакцию с полным механизмом и обсуждайте ее с сообществом.',
      view: 'Посмотреть',
    },
    home: {
      chemistryChat: 'Чат по химии',
      home: 'Главная',
      features: 'Возможности',
      about: 'О нас',
      community: 'Сообщество',
      eyebrow: 'Beyond curriculum · живая помощь по химии',
      title1: 'Самый живой',
      title2: 'чат по химии',
      title3: 'для нового старта',
      intro: 'Ximor объединяет вопросы, ответы наставников, формулы и энергию сообщества. Сейчас в центре чат, затем появятся уроки и практика.',
      openChat: 'Открыть чат',
      questionFlow: 'Лента вопросов',
      chemistrySections: 'Раздела химии',
      lessonsMode: 'Режим уроков',
      mentorAnswered: 'Наставник ответил',
      newDiscussions: '{{count}} новых обсуждений',
      writeQuestion: 'Написать вопрос…',
      featuresHeading: 'Чат уже работает, а структура готова для следующих разделов.',
      aboutHeading: 'Ximor — сообщество, которое вместе разбирается в химии.',
      aboutText: 'Наша цель — не сухой ответ, а понятный путь. Каждый вопрос сохраняется вместе с формулами, попытками и обсуждением, чтобы он помогал и следующим ученикам.',
      roadmap: 'План развития Ximor',
      now: 'Сейчас',
      next: 'Далее',
      nowItems: 'Чат, вопросы, ответы, рейтинг',
      nextItems: 'Уроки, практические задания, мини-олимпиады',
      later: 'Позже',
      laterItems: 'Комнаты наставников, группы, карта прогресса',
      join: 'Присоединиться к сообществу',
      joinText: 'Задавайте вопросы, публикуйте решения и изучайте химию вместе.',
      communityHeading: 'Откройте первое обсуждение. Всё остальное продолжится внутри.',
      communityChat: 'Чат сообщества',
      communitySections: 'Разделы сообщества',
      communityItems: ['Органическая химия', 'Подготовка к DTM', 'Олимпиадный спринт', 'Механизмы реакций', 'Аналитические задачи', 'Ответы наставников'],
      reactionSearch: 'Реакция H2SO4 + CuO…',
      grignardQuestion: 'Как работает механизм Гриньяра?',
      mentorMessage: 'Происходит нуклеофильная атака на карбонильный углерод.',
      learnerMessage: 'Значит, образуется первичный спирт?',
      pressureQuestion: 'Ле Шателье: что будет при повышении давления?',
      feature1Title: 'Чат на первом месте',
      feature1Text: 'Вопрос, решение, формула и изображение находятся в одной живой ленте.',
      feature2Title: 'Формулы уже готовы',
      feature2Text: 'Реакции, LaTeX, индексы и пошаговые решения выглядят аккуратно.',
      feature3Title: 'Наставники и рейтинг',
      feature3Text: 'Полезные ответы поднимаются выше, а активные участники заметны в сообществе.',
      feature4Title: 'Место для уроков',
      feature4Text: 'Структура готова для олимпиад, мини-курсов, тестов и практики.',
    },
  },
  en: {
    common: {
      back: 'Back',
      close: 'Close',
      loading: 'Loading…',
      retry: 'Try again',
      save: 'Save',
      saved: 'Saved',
      send: 'Send',
      open: 'Open',
      solved: 'Solved',
      copied: 'Copied',
      optional: 'optional',
      now: 'Now',
      today: 'Today',
      yesterday: 'Yesterday',
      language: 'Language',
    },
    time: {
      now: 'Now',
      minutesAgo: '{{count}} min ago',
      hoursAgo: '{{count}} hr ago',
      daysAgo: '{{count}} days ago',
    },
    nav: {
      main: 'Main sections',
      chat: 'Chat',
      olympiads: 'Olympiads',
      community: 'Community',
      ranking: 'Ranking',
      tools: 'Tools',
      news: 'News',
      profile: 'Profile',
      myProfile: 'My profile',
      login: 'Log in',
      logout: 'Log out',
      adminPanel: 'Admin panel',
      moderatorPanel: 'Moderator panel',
      mobile: 'Mobile navigation',
    },
    header: {
      tagline: 'Beyond Curriculum · Chemistry',
      search: 'Search questions, tags, or reactions',
      theme: 'Change theme',
      notifications: 'Notifications',
      allRead: 'all read',
      newCount: '{{count}} new',
      noNotifications: 'No notifications yet',
      askQuestion: 'Ask a question',
    },
    auth: {
      welcome: 'Welcome',
      createAccount: 'Create account',
      login: 'Log in',
      register: 'Sign up',
      fullName: 'Full name',
      username: 'Username',
      password: 'Password',
      minPassword: 'at least 6 characters',
      noAccount: "Don't have an account?",
      haveAccount: 'Already have an account?',
      registerAction: 'Sign up',
      loginAction: 'Log in',
      registerError: 'Registration failed',
      loginError: 'Login failed',
    },
    forum: {
      categories: 'Sections',
      all: 'All',
      organic: 'Organic chemistry',
      inorganic: 'Inorganic',
      physical: 'Physical',
      analytical: 'Analytical',
      recent: 'Recent',
      hot: 'Hot',
      unanswered: 'Unanswered',
      saved: 'Saved',
      feed: 'Question feed',
      compact: 'Compact',
      spacious: 'Spacious',
      masteryLevel: 'Mastery level',
      upvotes: 'Upvotes',
      answers: 'Answers',
      shared: 'Shared',
      dailySprint: 'Daily sprint',
      sprintText: 'Leave a helpful comment in three chemistry discussions today.',
      trendingTags: 'Trending tags',
      demoMode: 'Demo mode',
      demoText: 'The live API is responding slowly, so sample questions are shown.',
      noResults: 'No results found',
      noResultsHint: 'Try another word or subject.',
      pinned: 'Pinned topic',
      views: 'Views',
      copyLink: 'Copy question link',
      linkCopied: 'Link copied',
      upvote: 'Upvote',
      downvote: 'Downvote',
      voteUp: 'Upvote',
      voteDown: 'Downvote',
      voteRemoved: 'Vote removed',
      voteSaved: 'Vote saved',
      voteFailed: 'Could not save your vote. Try again',
      demoVote: 'Votes are not saved in demo mode',
      savedUpdated: 'Saved topics updated',
      answerSent: 'Answer sent',
      topicCreated: 'Topic created',
      topicCreateError: 'Could not create the topic. Try again.',
      follow: 'Follow',
      discussion: 'Discussion',
      usefulFirst: 'Most helpful first',
      answerCount: '{{count}} answers',
      noAnswers: 'No answers yet',
      noAnswersHint: 'The first clear answer will start this discussion.',
      writeAnswer: 'Write an answer',
      answerPlaceholder: 'Write a hint, formula, or full solution…',
      sendAnswer: 'Send answer',
      sending: 'Sending…',
    },
    composer: {
      newTopic: 'New topic',
      newQuestion: 'New chemistry question',
      write: 'Write',
      preview: 'Preview',
      title: 'Title',
      titlePlaceholder: 'For example: how does sulfuric acid react with CuO?',
      chemistry: 'Chemistry',
      formula: 'Formula',
      fraction: 'Fraction',
      reaction: 'Reaction',
      reversible: 'Reversible',
      charge: 'Charge',
      state: 'State',
      precipitate: 'Precipitate',
      formatting: 'Markdown formatting',
      bold: 'Bold',
      italic: 'Italic',
      list: 'List',
      quote: 'Quote',
      code: 'Code',
      link: 'Link',
      questionText: 'Question text',
      questionPlaceholder: 'Write your question — formulas can be inserted directly.',
      category: 'Section',
      tags: 'Tags',
      tagsHint: 'separate with commas',
      emptyPreview: 'Your question preview will appear here.',
      emptyTitle: 'No title yet',
      previewLabel: 'Preview',
      image: 'Image',
      removeImage: 'Remove image {{name}}',
      cancel: 'Cancel',
      creating: 'Saving…',
      create: 'Create topic',
    },
    question: {
      forum: 'Forum',
      notFound: 'Question not found',
      asked: 'Asked by',
      activity: 'Activity',
      status: 'Status',
      about: 'About this question',
      tags: 'Tags',
      acceptAnswer: 'Accept this answer',
      accepted: 'Accepted',
      answerAccepted: 'Answer accepted',
      markSolved: 'Solved',
      markOpen: 'Reopen',
      signInToAnswer: 'Log in to answer',
      loginOrRegister: 'Log in / Sign up',
      helpful: 'Helpful',
      unhelpful: 'Unhelpful',
      correct: 'Correct',
      incorrect: 'Incorrect',
      delete: 'Delete',
      answerDeleted: 'Answer deleted',
      answerMarked: 'Answer marked',
      questionSolved: 'Question solved',
      questionOpened: 'Question reopened',
      questionLinkCopied: 'Question link copied',
      answerLinkCopied: 'Answer link copied',
      copyAnswerLink: 'Copy answer link',
      copyFailed: 'Could not copy the link',
      genericError: 'Something went wrong',
      firstAnswer: 'Write the first answer!',
      confirmDelete: 'Delete this answer?',
    },
    insights: {
      liveRoom: 'Live room',
      connections: '{{count}} connections',
      topMentors: 'Most active users',
      community: 'Community',
      topUsers: 'Most active users',
      activeUser: 'Active member',
      userBadges: ['Most active answerer', 'Helped many people', 'Helpful solutions', 'Active in discussions', 'Member of the week'],
      weeklyChallenge: 'Weekly challenge',
      reactionMarathon: 'Reaction marathon',
      challengeText: 'Write one chemistry reaction with its full mechanism every day and discuss it with the community.',
      view: 'View',
    },
    home: {
      chemistryChat: 'Chemistry chat',
      home: 'Home',
      features: 'Features',
      about: 'About us',
      community: 'Community',
      eyebrow: 'Beyond curriculum · live chemistry help',
      title1: 'The liveliest',
      title2: 'chemistry chat',
      title3: 'for a fresh start',
      intro: 'Ximor brings questions, mentor answers, formulas, and community energy together. Chat is the main stage now, with lessons and practice coming next.',
      openChat: 'Open chat',
      questionFlow: 'Question feed',
      chemistrySections: 'Chemistry sections',
      lessonsMode: 'Lessons mode',
      mentorAnswered: 'A mentor replied',
      newDiscussions: '{{count}} new discussions',
      writeQuestion: 'Write a question…',
      featuresHeading: 'Chat works today, and the structure is ready for what comes next.',
      aboutHeading: 'Ximor is a community that understands chemistry together.',
      aboutText: 'The goal is simple: a clear path, not a dry answer. Every question is saved with formulas, attempts, and discussion so future learners can benefit too.',
      roadmap: 'Ximor roadmap',
      now: 'Now',
      next: 'Next',
      nowItems: 'Chat, questions, answers, ranking',
      nextItems: 'Lessons, practice sets, mini olympiads',
      later: 'Later',
      laterItems: 'Mentor rooms, cohorts, progress maps',
      join: 'Join the community',
      joinText: 'Ask questions, share solutions, and understand chemistry together.',
      communityHeading: 'Open the first discussion. Everything else continues inside.',
      communityChat: 'Community chat',
      communitySections: 'Community sections',
      communityItems: ['Organic chemistry', 'DTM preparation', 'Olympiad sprint', 'Reaction mechanisms', 'Analytical problems', 'Mentor answers'],
      reactionSearch: 'H2SO4 + CuO reaction…',
      grignardQuestion: 'How does the Grignard mechanism work?',
      mentorMessage: 'A nucleophilic attack occurs at the carbonyl carbon.',
      learnerMessage: 'So does it form a primary alcohol?',
      pressureQuestion: 'Le Chatelier: what happens when pressure rises?',
      feature1Title: 'Chat comes first',
      feature1Text: 'Questions, solutions, formulas, and images live in one active feed.',
      feature2Title: 'Chemistry formulas are ready',
      feature2Text: 'Reactions, LaTeX, subscripts, and step-by-step solutions render cleanly.',
      feature3Title: 'Mentors and rankings',
      feature3Text: 'Helpful answers rise while active contributors stand out in the community.',
      feature4Title: 'Room for lessons',
      feature4Text: 'The structure is ready for olympiads, mini-courses, tests, and practice.',
    },
  },
};

const LanguageContext = createContext(null);

function resolvePath(source, path) {
  return path.split('.').reduce((value, key) => value?.[key], source);
}

function interpolate(value, variables) {
  return Object.entries(variables).reduce(
    (text, [key, replacement]) => text.replaceAll(`{{${key}}}`, String(replacement)),
    value
  );
}

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    const stored = localStorage.getItem(STORAGE_KEY);
    return LANGUAGES.some((item) => item.code === stored) ? stored : DEFAULT_LANGUAGE;
  });

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = useCallback((nextLanguage) => {
    if (LANGUAGES.some((item) => item.code === nextLanguage)) {
      setLanguageState(nextLanguage);
    }
  }, []);

  const t = useCallback((key, variables = {}) => {
    const translated = resolvePath(translations[language], key);
    const fallback = resolvePath(translations[DEFAULT_LANGUAGE], key);
    const value = translated ?? fallback ?? key;
    return typeof value === 'string' ? interpolate(value, variables) : value;
  }, [language]);

  const value = useMemo(() => ({ language, setLanguage, t }), [language, setLanguage, t]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used inside LanguageProvider');
  return context;
}
