import { createContext, useCallback, useContext, useEffect, useMemo, useState } from 'react';

const STORAGE_KEY = 'ximor_language';
const DEFAULT_LANGUAGE = 'uz';

export const LANGUAGES = [
  { code: 'uz', short: 'UZ', name: "O'zbekcha" },
  { code: 'ru', short: 'RU', name: 'Русский' },
  { code: 'en', short: 'EN', name: 'English' },
];

const translations = {
  uz: {
    common: {
      back: 'Orqaga',
      close: 'Yopish',
      loading: 'Yuklanmoqda…',
      retry: "Qayta urinib ko'ring",
      save: 'Saqlash',
      saved: 'Saqlangan',
      send: 'Yuborish',
      open: 'Ochiq',
      solved: 'Yechilgan',
      copied: 'Nusxalandi',
      optional: 'ixtiyoriy',
      now: 'Hozir',
      today: 'Bugun',
      yesterday: 'Kecha',
      language: 'Til',
      soon: 'tez orada',
      live: 'jonli',
    },
    time: {
      now: 'Hozir',
      minutesAgo: '{{count}} daq oldin',
      hoursAgo: '{{count}} soat oldin',
      daysAgo: '{{count}} kun oldin',
    },
    nav: {
      main: "Asosiy bo'limlar",
      chat: 'Forum',
      messages: 'Xabarlar',
      olympiads: 'Olimpiadalar',
      community: 'Hamjamiyat',
      ranking: 'Reyting',
      tools: 'Asboblar',
      news: 'Yangiliklar',
      profile: 'Profil',
      myProfile: 'Profilim',
      savedQuestions: 'Saqlangan savollar',
      login: 'Kirish',
      logout: 'Chiqish',
      adminRole: 'Admin',
      moderatorRole: 'Moderator',
      adminPanel: 'Admin Panel',
      moderatorPanel: 'Moderator Panel',
      mobile: 'Mobil navigatsiya',
    },
    header: {
      tagline: 'Beyond Curriculum · Kimyo',
      search: 'Savol, teg yoki reaksiya qidiring',
      theme: 'Mavzuni almashtirish',
      notifications: 'Bildirishnomalar',
      allRead: "hammasi o'qilgan",
      newCount: '{{count}} yangi',
      noNotifications: "Hali bildirishnoma yo'q",
      askQuestion: 'Savol berish',
    },
    auth: {
      welcome: 'Xush kelibsiz',
      createAccount: 'Hisob yaratish',
      login: 'Kirish',
      register: "Ro'yxatdan o'tish",
      fullName: "To'liq ism",
      email: 'Email',
      username: 'Username',
      password: 'Parol',
      minPassword: 'kamida 6 ta belgi',
      noAccount: "Hisob yo'qmi?",
      haveAccount: 'Hisob bormi?',
      registerAction: "Ro'yxatdan o'ting",
      loginAction: 'Kiring',
      registerError: "Ro'yxatdan o'tishda xato",
      loginError: 'Kirish xatosi',
    },
    forum: {
      categories: "Bo'limlar",
      all: 'Hammasi',
      organic: 'Organik kimyo',
      inorganic: 'Anorganik',
      physical: 'Fizikaviy',
      analytical: 'Analitik',
      recent: "So'nggi",
      hot: 'Qaynoq',
      unanswered: 'Javobsiz',
      saved: 'Saqlangan',
      feed: 'Savollar oqimi',
      compact: 'Ixcham',
      spacious: 'Keng',
      masteryLevel: 'Mastery darajasi',
      upvotes: 'Ovozlar',
      answers: 'Javoblar',
      shared: 'Ulashdi',
      dailySprint: 'Kunlik sprint',
      sprintText: 'Bugun uchta kimyo muhokamasida foydali izoh qoldiring.',
      trendingTags: 'Ommabop teglar',
      demoMode: 'Demo rejim',
      demoText: "Live API sekin javob bermoqda, shuning uchun namunaviy savollar ko'rsatilmoqda.",
      noResults: 'Natija topilmadi',
      noResultsHint: "Boshqa so'z yoki fan bilan qidirib ko'ring.",
      noSaved: "Hali saqlangan savol yo'q",
      noSavedHint: "Kerakli savolni keyinroq ko'rish uchun bookmark tugmasini bosing.",
      signInForSaved: "Saqlangan savollarni ko'rish uchun kiring",
      signInForSavedHint: 'Saqlangan savollar hisobingizda saqlanadi.',
      pinned: 'Mahkamlangan mavzu',
      views: "Ko'rishlar",
      copyLink: 'Savol havolasini nusxalash',
      linkCopied: 'Havola nusxalandi',
      upvote: 'Yuqoriga ovoz berish',
      downvote: 'Pastga ovoz berish',
      voteUp: 'Yuqoriga ovoz',
      voteDown: 'Pastga ovoz',
      voteRemoved: 'Ovoz olib tashlandi',
      voteSaved: 'Ovoz saqlandi',
      voteFailed: "Ovoz saqlanmadi. Qayta urinib ko'ring",
      demoVote: 'Demo rejimda ovozlar saqlanmaydi',
      savedUpdated: 'Saqlanganlar yangilandi',
      answerSent: 'Javob yuborildi',
      topicCreated: 'Mavzu yaratildi',
      topicCreateError: "Mavzu yaratishda xato. Qayta urinib ko'ring.",
      follow: 'Kuzatish',
      discussion: 'Muhokama',
      usefulFirst: 'Eng foydalilari yuqorida',
      answerCount: '{{count}} ta javob',
      noAnswers: "Hali javob yo'q",
      noAnswersHint: 'Birinchi aniq javob shu muhokamani boshlab beradi.',
      writeAnswer: 'Javob yozish',
      answerPlaceholder: "Qisqa ishora, formula yoki to'liq yechim yozing…",
      sendAnswer: 'Javob yuborish',
      sending: 'Yuborilmoqda…',
    },
    messages: {
      eyebrow: 'Shaxsiy chat',
      title: 'Xabarlar',
      people: 'Foydalanuvchilar',
      conversations: 'Suhbatlar',
      searchUsers: 'Foydalanuvchi qidiring',
      noConversations: "Hali suhbat yo'q",
      noUsers: 'Foydalanuvchi topilmadi',
      noMessages: 'Hali xabar yozilmagan',
      startChat: 'Yozish',
      youPrefix: 'Siz: ',
      newMessage: 'Yangi',
      selectConversation: 'Suhbatni tanlang',
      selectConversationText: 'Chap tomondan mavjud suhbatni oching yoki foydalanuvchi bilan yangi chat boshlang.',
      emptyThread: 'Birinchi xabarni yozing',
      emptyThreadText: 'Bu suhbat hali boshlanmagan.',
      messagePlaceholder: 'Xabar yozing…',
      sendMessage: 'Yuborish',
      sending: 'Yuborilmoqda…',
      loginTitle: 'Xabarlar uchun tizimga kiring',
      loginText: "Foydalanuvchilar bilan shaxsiy suhbat boshlash uchun hisobingizga kiring yoki ro'yxatdan o'ting.",
      loginAction: 'Kirish',
      loadError: "Xabarlar yuklanmadi. Qayta urinib ko'ring.",
      sendError: "Xabar yuborilmadi. Qayta urinib ko'ring.",
      startError: "Suhbat ochilmadi. Qayta urinib ko'ring.",
    },
    composer: {
      newTopic: 'Yangi mavzu',
      newQuestion: 'Yangi kimyo savoli',
      write: 'Yozish',
      preview: "Ko'rib chiqish",
      title: 'Sarlavha',
      titlePlaceholder: 'Masalan: sulfat kislotaning CuO bilan reaksiyasi qanday boradi?',
      chemistry: 'Kimyo',
      formula: 'Formula',
      fraction: 'Kasr',
      reaction: 'Reaksiya',
      reversible: 'Qaytar',
      charge: 'Zaryad',
      state: 'Holat',
      precipitate: "Cho'kma",
      formatting: 'Markdown formatlash',
      mathKeyboard: 'Klaviatura',
      formulaGroup: 'Formula bo‘limi',
      bold: 'Qalin',
      italic: 'Kursiv',
      list: "Ro'yxat",
      quote: 'Iqtibos',
      code: 'Kod',
      link: 'Havola',
      questionText: 'Savol matni',
      questionPlaceholder: "Savolingizni yozing — formulalarni to'g'ridan-to'g'ri qo'shing.",
      category: "Bo'lim",
      tags: 'Teglar',
      tagsHint: 'vergul bilan ajrating',
      emptyPreview: "Savol matni yozilganda bu yerda ko'rinadi.",
      emptyTitle: 'Sarlavha hali yozilmagan',
      previewLabel: "Ko'rinishi",
      image: 'Rasm',
      removeImage: '{{name}} rasmini olib tashlash',
      cancel: 'Bekor qilish',
      creating: 'Saqlanmoqda…',
      create: 'Mavzu yaratish',
    },
    question: {
      forum: 'Forum',
      notFound: 'Savol topilmadi',
      asked: "So'radi",
      createdAt: 'Yaratilgan vaqt',
      editQuestion: 'Savolni tahrirlash',
      editQuestionTitle: "Savol matnini yangilash",
      saveQuestion: 'Saqlash',
      savingQuestion: 'Saqlanmoqda…',
      questionUpdated: 'Savol yangilandi',
      questionUpdateError: "Savolni yangilab bo'lmadi",
      activity: 'Faollik',
      status: 'Holat',
      about: 'Savol haqida',
      tags: 'Teglar',
      acceptAnswer: 'Bu javobni qabul qilish',
      accepted: 'Qabul qilindi',
      answerAccepted: 'Javob qabul qilindi',
      markSolved: 'Yechildi',
      markOpen: 'Ochiq qilish',
      signInToAnswer: 'Javob berish uchun tizimga kiring',
      loginOrRegister: "Kirish / Ro'yxatdan o'tish",
      helpful: 'Foydali',
      unhelpful: 'Foydasiz',
      correct: "To'g'ri",
      incorrect: "Noto'g'ri",
      delete: "O'chirish",
      deleteQuestion: "Savolni o'chirish",
      answerDeleted: "Javob o'chirildi",
      questionDeleted: "Savol o'chirildi",
      answerMarked: 'Javob belgilandi',
      questionSolved: 'Savol yechildi',
      questionOpened: 'Savol ochiq qilindi',
      questionLinkCopied: 'Savol havolasi nusxalandi',
      answerLinkCopied: 'Javob havolasi nusxalandi',
      copyAnswerLink: 'Javob havolasini nusxalash',
      reply: 'Javob berish',
      replyPlaceholder: 'Shu javobga fikringizni yozing…',
      sendReply: 'Yuborish',
      sendingReply: 'Yuborilmoqda…',
      replySent: 'Javobga reaksiya yuborildi',
      copyFailed: "Havolani nusxalab bo'lmadi",
      genericError: 'Xato yuz berdi',
      firstAnswer: 'Birinchi javobni yozing!',
      confirmDelete: "Bu javobni o'chirasizmi?",
      confirmQuestionDelete: "Bu savolni o'chirasizmi? Bu amalni qaytarib bo'lmaydi.",
    },
    insights: {
      liveRoom: 'Jonli xona',
      connections: '{{count}} ulanish',
      topMentors: 'Eng faol foydalanuvchilar',
      community: 'Hamjamiyat',
      topUsers: 'Eng faol foydalanuvchilar',
      activeUser: 'Faol ishtirokchi',
      userBadges: ['Eng faol javobchi', "Ko'p yordam bergan", 'Foydali yechimlar', 'Muhokamada faol', 'Haftaning ishtirokchisi'],
      weeklyChallenge: 'Hafta chaqiruvi',
      reactionMarathon: 'Reaksiya marafoni',
      challengeText: "Har kuni bitta kimyo reaksiyasini to'liq mexanizm bilan yozing va community bilan muhokama qiling.",
      view: "Ko'rish",
    },
    home: {
      chemistryChat: 'Kimyo forum',
      home: 'Bosh sahifa',
      features: 'Imkoniyatlar',
      about: 'Biz haqimizda',
      community: 'Hamjamiyat',
      eyebrow: 'Beyond curriculum · jonli kimyo yordami',
      title1: 'Eng jonli',
      title2: 'kimyo forum',
      title3: 'uchun yangi start',
      intro: "ChOUZ Team — savollar, mentor javoblari, formulalar va hamjamiyat energiyasi bitta joyda. Hozir asosiy sahna forum, keyin darslar va mashq bo'limlari ham qo'shiladi.",
      openChat: 'Forumni ochish',
      questionFlow: 'Savol oqimi',
      chemistrySections: "Kimyo bo'limi",
      lessonsMode: 'Darslar rejimi',
      mentorAnswered: 'Mentor javob berdi',
      newDiscussions: '{{count}} yangi muhokama',
      writeQuestion: 'Savol yozish…',
      featuresHeading: "Forum hozir ishlaydi, keyingi bo'limlar uchun joy allaqachon tayyor.",
      aboutHeading: 'ChOUZ Team — kimyoni birga tushunadigan hamjamiyat.',
      aboutText: "Maqsad oddiy: quruq javob emas, tushunarli yo'l. Har bir savol formulasi, urinishlari va muhokamasi bilan saqlanadi, shunda yangi o'quvchi ham undan foyda oladi.",
      roadmap: 'ChOUZ Team rivojlanish rejasi',
      now: 'Hozir',
      next: 'Keyin',
      nowItems: 'Forum, savollar, javoblar, reyting',
      nextItems: 'Darslar, mashqlar, mini olimpiadalar',
      later: 'Keyinroq',
      laterItems: 'Mentor xonalari, guruhlar, rivojlanish xaritasi',
      join: "Hamjamiyatga qo'shiling",
      joinText: "Savolingizni bering, yechim yozing va kimyoni birga tushuning.",
      communityHeading: "Birinchi muhokamani oching. Qolgan harakat ichkarida davom etadi.",
      communityChat: 'Hamjamiyat forumi',
      communitySections: "Hamjamiyat bo'limlari",
      communityItems: ['Organik kimyo', 'DTM tayyorgarlik', 'Olimpiada sprinti', 'Reaksiya mexanizmlari', 'Analitik masalalar', 'Mentor javoblari'],
      reactionSearch: 'H2SO4 + CuO reaksiyasi…',
      grignardQuestion: 'Grignard mexanizmi qanday ishlaydi?',
      mentorMessage: "Karbonil uglerodiga nukleofil hujum bo'ladi.",
      learnerMessage: "Demak birlamchi spirt hosil bo'ladimi?",
      pressureQuestion: 'Le Chatelier: bosim oshsa?',
      feature1Title: "Forum birinchi o'rinda",
      feature1Text: "Savol, yechim, formula va rasm bitta jonli oqimda.",
      feature2Title: 'Kimyo formulalari tayyor',
      feature2Text: "Reaksiya, LaTeX, indeks va bosqichma-bosqich yechimlar chiroyli ko'rinadi.",
      feature3Title: 'Mentorlar va reyting',
      feature3Text: "Foydali javoblar yuqoriga ko'tariladi, faol yordamchilar esa hamjamiyatda ko'rinadi.",
      feature4Title: 'Darslar uchun joy bor',
      feature4Text: "Olimpiada, mini-kurs, test va mashq rejimlari uchun tuzilma tayyor.",
    },
    profile: {
      notFound: 'Foydalanuvchi topilmadi',
      since: '{{date}} dan beri',
      points: 'Ball',
      questions: 'Savol',
      answers: 'Javob',
      accepted: 'Qabul',
      questionsTab: 'Savollar ({{count}})',
      answersTab: 'Javoblar ({{count}})',
      noQuestions: 'Hali savol berilmagan',
      noAnswers: 'Hali javob berilmagan',
      answerCount: '{{count}} javob',
      pointCount: '{{count}} ball',
      viewCount: "{{count}} ko'rish",
      acceptedBadge: 'Qabul qilindi',
      publicProfile: 'Ochiq profil',
      editProfile: 'Profilni tahrirlash',
      displayName: "Ko'rinadigan ism",
      username: 'Username',
      role: 'Rol',
      headline: 'Qisqa sarlavha',
      bio: 'Bio',
      about: 'Haqida',
      noBio: "Hali bio yozilmagan.",
      location: 'Joylashuv',
      website: 'Website',
      studyGoal: "O'qish maqsadi",
      profileDetails: "Ma'lumotlar",
      noDetails: "Hali qo'shimcha ma'lumot yo'q",
      interestsLabel: 'Qiziqishlar',
      interestsHint: 'organik kimyo, DTM, titrlash',
      noInterests: "Hali qiziqishlar qo'shilmagan.",
      avatarPhoto: 'Profil rasmi',
      coverPhoto: 'Cover rasmi',
      coverSamples: 'Tayyor fonlar',
      avatarSamples: 'Tayyor avatarlar',
      coverPresetLab: 'Laboratoriya',
      coverPresetOrbit: 'Orbita',
      coverPresetNotebook: 'Daftar',
      coverPresetCrystal: 'Kristall',
      coverPresetReaction: 'Reaksiya',
      avatarPresetChemist: 'Kimyogar',
      avatarPresetNeon: 'Neon',
      avatarPresetMint: 'Yumshoq',
      avatarPresetViolet: 'Violet',
      avatarPresetGraphite: 'Grafit',
      avatarPresetSolar: 'Quyosh',
      removePhoto: 'Olib tashlash',
      saveChanges: "O'zgarishlarni saqlash",
      saving: 'Saqlanmoqda…',
      profileUpdated: 'Profil yangilandi',
      editError: "Profil saqlanmadi. Qayta urinib ko'ring.",
      imageError: "Rasmni yuklab bo'lmadi.",
      messageUser: 'Xabar yozish',
      contribution: 'Faollik',
      solvedRate: 'Qabul ulushi',
      completed: 'Qabul qilingan javoblar',
      tiers: { diamond: 'OLMOS', platinum: 'PLATINA', gold: 'OLTIN', silver: 'KUMUSH', learner: 'SHOGIRD' },
    },
    ranking: {
      period: 'Davr',
      periods: { week: 'Bu hafta', month: 'Bu oy', quarter: 'Bu chorak', year: 'Yillik', all: 'Hamma vaqt' },
      rules: 'Reyting qanday ishlaydi',
      acceptedRule: 'Javob qabul',
      upvoteRule: 'Yuqori ovoz',
      olympiadRule: "Olimpiada g'olibligi",
      mentorRule: "Mentor tasdig'i",
      coefficient: 'koeffitsient',
      leaders: 'Hafta yetakchilari',
      mostActive: 'Eng faol',
      chemists: 'kimyogarlar reytingi',
      intro: "Reyting foydalanuvchining profil bali asosida tuziladi. Hozir avtomatik ball asosan qabul qilingan javoblardan yoziladi; ovozlar esa savol va javoblarning ko'rinish tartibiga ta'sir qiladi.",
      ruleRows: [
        { label: 'Qabul qilingan javob', value: '+50 ball', detail: 'Savol egasi yoki moderator javobni qabul qilsa, javob muallifiga profil bali qo‘shiladi.' },
        { label: 'Javob ovozlari', value: 'Javob reytingi', detail: 'Upvote/downvote javobning o‘z score qiymatini o‘zgartiradi va foydali javoblarni yuqoriroq ko‘rsatadi.' },
        { label: 'Savol ovozlari', value: 'Savol reytingi', detail: 'Savolga berilgan ovozlar savol score qiymatini o‘zgartiradi, lekin muallif profil baliga qo‘shilmaydi.' },
        { label: 'Davr filtrlari', value: 'Ball logi', detail: 'Hafta, oy, chorak va yil reytingi shu davrda yozilgan ball loglari bo‘yicha hisoblanadi.' },
      ],
      rulesNote: "Hamma vaqt reytingi foydalanuvchining umumiy profil balidan olinadi. Demo yoki admin tomonidan kiritilgan ballar ham umumiy ballda ko'rinishi mumkin.",
      user: 'Foydalanuvchi',
      points: 'Ball',
      accepted: 'Qabul',
      change: "O'zg.",
    },
    communityPage: {
      communities: 'Hamjamiyatlar',
      purpose: 'Maqsad',
      usefulPages: 'Foydali kimyo sahifalari',
      purposeText: "Bu bo'limda ChOUZ Team foydalanuvchilari uchun kerakli hamjamiyat saytlari, materiallar va rasmiy kanallar bir joyga yig'iladi.",
      ourCommunity: 'Bizning hamjamiyat',
      title: 'Kimyo hamjamiyati',
      intro: "Kimyo o'rganuvchilari uchun foydali hamjamiyatlar, ularning saytlari, kutubxonalari va jamoa ma'lumotlari shu yerda jamlanadi.",
      openUac: "UAC saytiga o'tish",
      library: 'Kutubxona',
      oneSite: 'Hozircha 1 ta sayt',
      websites: 'Hamjamiyat saytlari',
      uacTeam: 'UAC jamoasi',
      membersInfo: "A'zolar va ma'lumotlar",
      contact: 'Aloqa',
      source: 'Manba',
      officialPage: 'Rasmiy sahifa',
      sourceText: "Jamoa ma'lumotlari UAC sahifasidan olindi. Keyinroq boshqa hamjamiyat saytlari ham shu formatda qo'shiladi.",
      website: 'sayt',
      teamMembers: "jamoa a'zolari",
      socialChannels: 'ijtimoiy kanal',
      openSite: 'Saytni ochish',
      websiteLabel: 'Hamjamiyat sayti',
      teamLabel: '{{name}} jamoasi',
    },
    news: {
      title: 'Dunyo kimyo yangiliklari',
      intro: "ScienceDaily orqali dunyo bo'ylab kimyo fanining so'nggi kashfiyotlari",
      error: "Yangiliklar yuklanmadi. Qayta urinib ko'ring.",
    },
    tools: {
      eyebrow: 'Kimyo asboblari',
      title: 'Hisoblash markazi',
      intro: "Tenglamani balanslang, moddaning tarkibini hisoblang va reagentdan qancha mahsulot chiqishini bosqichma-bosqich toping.",
      tabsLabel: 'Kimyo hisoblash asboblari',
      toolCount: '3 ta asbob',
      workspace: 'Bitta kimyo ish maydoni',
      workspaceText: "Tenglama koeffitsiyentlari stoxiometriya hisobiga to'g'ridan-to'g'ri uzatiladi. Natijalar brauzerning o'zida hisoblanadi.",
      checks: ['Oddiy formula va qavslar', '94 ta element atom massasi', 'Gram, mol va zarrachalar', 'Yechim bosqichlari bilan javob'],
      rule: 'Hisoblash qoidasi',
      theoretical: 'Natija nazariy qiymat',
      theoreticalText: "Stoxiometriya asbobi reagent tozaligi va reaksiya chiqishini 100% deb oladi. Laboratoriya natijasi bundan farq qilishi mumkin.",
      balance: 'Tenglashtirish',
      balanceCaption: 'Atomlar balansi',
      molarMass: 'Molyar massa',
      massCaption: 'Tarkib va konversiya',
      stoichiometry: 'Stoxiometriya',
      stoichCaption: 'Reagentdan mahsulotga',
      calculationFailed: "Hisoblab bo'lmadi",
      amountUnit: 'Miqdor birligi',
      reactionEquation: 'Reaksiya tenglamasi',
      balancedEquation: 'Tenglashtirilgan tenglama',
      reactants: 'Reagentlar',
      products: 'Mahsulotlar',
      reactionType: 'Reaksiya turi',
      element: 'Element',
      left: 'Chap',
      right: "O'ng",
      status: 'Holat',
      whatHappened: "Nima sodir bo'ldi?",
      copyAsQuestion: 'Forum savoli sifatida nusxalash',
      conversion: 'Miqdorni aylantirish',
      amount: 'Miqdor',
      mass: 'Massa',
      substanceAmount: 'Modda miqdori',
      particles: 'Zarrachalar',
      massComposition: 'Massa tarkibi',
      count: 'Soni',
      atomicMass: 'Atom massasi',
      share: 'Ulushi',
      automaticBalance: 'Avtomatik balans',
      initialAmount: "Boshlang'ich miqdor",
      yieldNote: '100% reaksiya chiqishi qabul qilinadi.',
      theoreticalResult: 'Nazariy natija',
      productAmount: 'Mahsulot miqdori',
      coefficientRatio: 'Koeffitsiyent nisbati',
      solutionSteps: 'Yechim bosqichlari',
      balanced: 'Teng',
      errorStatus: 'Xato',
      substanceFormula: 'Modda formulasi',
      atomTotal: 'Bir molekulada jami {{count}} ta atom.',
      reactionToBalance: 'Tenglashtiriladigan reaksiya',
      givenSubstance: 'Berilgan modda',
      targetSubstance: 'Topiladigan modda',
      reactant: 'reagent',
      product: 'mahsulot',
      ratioStep: 'Tenglama nisbati bo‘yicha × {{ratio}}',
      molarMassStep: '{{formula}} molyar massasi:',
    },
    admin: {
      loginRequired: 'Kirish kerak',
      noPermission: "Moderator huquqi yo'q",
      deniedText: 'Bu sahifaga faqat admin yoki moderatorlar kira oladi.',
      firstAdminTitle: 'Birinchi adminni yaratish',
      firstAdminText: "Agar hali admin bo'lmasa, shu hisobni birinchi admin qiling. Agar admin allaqachon bor bo'lsa, mavjud admin sizni tayinlashi kerak.",
      firstAdminAction: "Meni birinchi admin qilish",
      firstAdminWorking: 'Tekshirilmoqda…',
      firstAdminDone: "Admin huquqi berildi. Sahifa yangilanmoqda…",
      firstAdminError: "Admin qilish imkoni bo'lmadi",
      home: 'Bosh sahifaga',
      adminCenter: 'ChOUZ Team boshqaruv markazi',
      moderatorCenter: 'Moderator boshqaruv markazi',
      today: '+{{count}} bugun',
      users: 'Foydalanuvchilar',
      topics: 'Mavzular',
      answers: 'Javoblar',
      moderators: 'Moderatorlar',
      banned: 'Bloklangan',
      overview: "Ko'rinish",
      content: 'Kontent',
      permissions: 'Huquqlar',
      announcement: "E'lon",
      recentTopics: "So'nggi mavzular",
      recentAnswers: "So'nggi javoblar",
      allUsers: 'Barcha foydalanuvchilar ({{count}})',
      searchUsers: "Ism, email yoki username bo'yicha qidirish…",
      user: 'Foydalanuvchi',
      points: 'Ball',
      status: 'Holat',
      actions: 'Amallar',
      roleRights: 'Rol huquqlari',
      adminAssigns: "Admin moderator huquqlarini o'zgartiradi",
      section: "Bo'lim",
      right: 'Huquq',
      allowed: 'Bor',
      denied: "Yo'q",
      turnOnRight: 'Moderatorga berish',
      turnOffRight: 'Moderatordan olish',
      recent50: "So'nggi 50 ta",
      title: 'Sarlavha',
      author: 'Muallif',
      answer: 'Javob',
      sendAnnouncement: "Barcha foydalanuvchilarga e'lon yuborish",
      announcementHelp: "E'lon barcha ro'yxatdan o'tgan foydalanuvchilarning bildirishnomalariga yuboriladi.",
      announcementPlaceholder: "E'lon matnini kiriting… (eng ko'pi 500 belgi)",
      sending: 'Yuborilmoqda…',
      send: 'Yuborish',
    },
  },
  ru: {
    common: {
      back: 'Назад',
      close: 'Закрыть',
      loading: 'Загрузка…',
      retry: 'Попробовать снова',
      save: 'Сохранить',
      saved: 'Сохранено',
      send: 'Отправить',
      open: 'Открыт',
      solved: 'Решён',
      copied: 'Скопировано',
      optional: 'необязательно',
      now: 'Сейчас',
      today: 'Сегодня',
      yesterday: 'Вчера',
      language: 'Язык',
      soon: 'скоро',
      live: 'онлайн',
    },
    time: {
      now: 'Сейчас',
      minutesAgo: '{{count}} мин назад',
      hoursAgo: '{{count}} ч назад',
      daysAgo: '{{count}} дн назад',
    },
    nav: {
      main: 'Основные разделы',
      chat: 'Форум',
      messages: 'Сообщения',
      olympiads: 'Олимпиады',
      community: 'Сообщество',
      ranking: 'Рейтинг',
      tools: 'Инструменты',
      news: 'Новости',
      profile: 'Профиль',
      myProfile: 'Мой профиль',
      savedQuestions: 'Сохранённые вопросы',
      login: 'Войти',
      logout: 'Выйти',
      adminRole: 'Админ',
      moderatorRole: 'Модератор',
      adminPanel: 'Панель администратора',
      moderatorPanel: 'Панель модератора',
      mobile: 'Мобильная навигация',
    },
    header: {
      tagline: 'Beyond Curriculum · Химия',
      search: 'Поиск вопроса, тега или реакции',
      theme: 'Сменить тему',
      notifications: 'Уведомления',
      allRead: 'всё прочитано',
      newCount: '{{count}} новых',
      noNotifications: 'Уведомлений пока нет',
      askQuestion: 'Задать вопрос',
    },
    auth: {
      welcome: 'Добро пожаловать',
      createAccount: 'Создать аккаунт',
      login: 'Войти',
      register: 'Регистрация',
      fullName: 'Полное имя',
      email: 'Email',
      username: 'Имя пользователя',
      password: 'Пароль',
      minPassword: 'минимум 6 символов',
      noAccount: 'Нет аккаунта?',
      haveAccount: 'Уже есть аккаунт?',
      registerAction: 'Зарегистрируйтесь',
      loginAction: 'Войдите',
      registerError: 'Ошибка регистрации',
      loginError: 'Ошибка входа',
    },
    forum: {
      categories: 'Разделы',
      all: 'Все',
      organic: 'Органическая химия',
      inorganic: 'Неорганическая',
      physical: 'Физическая',
      analytical: 'Аналитическая',
      recent: 'Новые',
      hot: 'Популярные',
      unanswered: 'Без ответа',
      saved: 'Сохранённые',
      feed: 'Лента вопросов',
      compact: 'Компактно',
      spacious: 'Просторно',
      masteryLevel: 'Уровень мастерства',
      upvotes: 'Голоса',
      answers: 'Ответы',
      shared: 'Поделился',
      dailySprint: 'Ежедневный спринт',
      sprintText: 'Оставьте сегодня полезный комментарий в трёх обсуждениях по химии.',
      trendingTags: 'Популярные теги',
      demoMode: 'Демо-режим',
      demoText: 'Live API отвечает медленно, поэтому показаны демонстрационные вопросы.',
      noResults: 'Ничего не найдено',
      noResultsHint: 'Попробуйте другое слово или раздел.',
      noSaved: 'Сохранённых вопросов пока нет',
      noSavedHint: 'Нажмите закладку на нужном вопросе, чтобы вернуться к нему позже.',
      signInForSaved: 'Войдите, чтобы увидеть сохранённые вопросы',
      signInForSavedHint: 'Сохранённые вопросы хранятся в вашем аккаунте.',
      pinned: 'Закреплённая тема',
      views: 'Просмотры',
      copyLink: 'Скопировать ссылку на вопрос',
      linkCopied: 'Ссылка скопирована',
      upvote: 'Проголосовать за',
      downvote: 'Проголосовать против',
      voteUp: 'Голос за',
      voteDown: 'Голос против',
      voteRemoved: 'Голос отменён',
      voteSaved: 'Голос сохранён',
      voteFailed: 'Не удалось сохранить голос. Попробуйте снова',
      demoVote: 'В демо-режиме голоса не сохраняются',
      savedUpdated: 'Сохранённые обновлены',
      answerSent: 'Ответ отправлен',
      topicCreated: 'Тема создана',
      topicCreateError: 'Не удалось создать тему. Попробуйте снова.',
      follow: 'Следить',
      discussion: 'Обсуждение',
      usefulFirst: 'Сначала самые полезные',
      answerCount: '{{count}} ответов',
      noAnswers: 'Ответов пока нет',
      noAnswersHint: 'Первый точный ответ начнёт это обсуждение.',
      writeAnswer: 'Написать ответ',
      answerPlaceholder: 'Напишите подсказку, формулу или полное решение…',
      sendAnswer: 'Отправить ответ',
      sending: 'Отправка…',
    },
    messages: {
      eyebrow: 'Личный чат',
      title: 'Сообщения',
      people: 'Пользователи',
      conversations: 'Диалоги',
      searchUsers: 'Найти пользователя',
      noConversations: 'Диалогов пока нет',
      noUsers: 'Пользователи не найдены',
      noMessages: 'Сообщений пока нет',
      startChat: 'Написать',
      youPrefix: 'Вы: ',
      newMessage: 'Новое',
      selectConversation: 'Выберите диалог',
      selectConversationText: 'Откройте существующий диалог слева или начните новый чат с пользователем.',
      emptyThread: 'Напишите первое сообщение',
      emptyThreadText: 'Этот диалог еще не начался.',
      messagePlaceholder: 'Напишите сообщение…',
      sendMessage: 'Отправить',
      sending: 'Отправка…',
      loginTitle: 'Войдите, чтобы открыть сообщения',
      loginText: 'Войдите или зарегистрируйтесь, чтобы общаться с другими пользователями лично.',
      loginAction: 'Войти',
      loadError: 'Не удалось загрузить сообщения. Попробуйте снова.',
      sendError: 'Не удалось отправить сообщение. Попробуйте снова.',
      startError: 'Не удалось открыть диалог. Попробуйте снова.',
    },
    composer: {
      newTopic: 'Новая тема',
      newQuestion: 'Новый вопрос по химии',
      write: 'Написать',
      preview: 'Предпросмотр',
      title: 'Заголовок',
      titlePlaceholder: 'Например: как реагирует серная кислота с CuO?',
      chemistry: 'Химия',
      formula: 'Формула',
      fraction: 'Дробь',
      reaction: 'Реакция',
      reversible: 'Обратимая',
      charge: 'Заряд',
      state: 'Состояние',
      precipitate: 'Осадок',
      formatting: 'Форматирование Markdown',
      mathKeyboard: 'Клавиатура',
      formulaGroup: 'Раздел формул',
      bold: 'Жирный',
      italic: 'Курсив',
      list: 'Список',
      quote: 'Цитата',
      code: 'Код',
      link: 'Ссылка',
      questionText: 'Текст вопроса',
      questionPlaceholder: 'Напишите вопрос — формулы можно вставлять прямо в текст.',
      category: 'Раздел',
      tags: 'Теги',
      tagsHint: 'разделяйте запятыми',
      emptyPreview: 'Здесь появится предварительный просмотр вопроса.',
      emptyTitle: 'Заголовок ещё не написан',
      previewLabel: 'Предпросмотр',
      image: 'Изображение',
      removeImage: 'Удалить изображение {{name}}',
      cancel: 'Отмена',
      creating: 'Сохранение…',
      create: 'Создать тему',
    },
    question: {
      forum: 'Форум',
      notFound: 'Вопрос не найден',
      asked: 'Автор',
      createdAt: 'Дата создания',
      editQuestion: 'Редактировать вопрос',
      editQuestionTitle: 'Обновить текст вопроса',
      saveQuestion: 'Сохранить',
      savingQuestion: 'Сохранение…',
      questionUpdated: 'Вопрос обновлён',
      questionUpdateError: 'Не удалось обновить вопрос',
      activity: 'Активность',
      status: 'Статус',
      about: 'О вопросе',
      tags: 'Теги',
      acceptAnswer: 'Принять этот ответ',
      accepted: 'Принят',
      answerAccepted: 'Ответ принят',
      markSolved: 'Решён',
      markOpen: 'Сделать открытым',
      signInToAnswer: 'Войдите, чтобы ответить',
      loginOrRegister: 'Войти / Регистрация',
      helpful: 'Полезный',
      unhelpful: 'Бесполезный',
      correct: 'Верный',
      incorrect: 'Неверный',
      delete: 'Удалить',
      deleteQuestion: 'Удалить вопрос',
      answerDeleted: 'Ответ удалён',
      questionDeleted: 'Вопрос удалён',
      answerMarked: 'Ответ отмечен',
      questionSolved: 'Вопрос решён',
      questionOpened: 'Вопрос снова открыт',
      questionLinkCopied: 'Ссылка на вопрос скопирована',
      answerLinkCopied: 'Ссылка на ответ скопирована',
      copyAnswerLink: 'Скопировать ссылку на ответ',
      reply: 'Ответить',
      replyPlaceholder: 'Напишите ответ к этому ответу…',
      sendReply: 'Отправить',
      sendingReply: 'Отправка…',
      replySent: 'Ответ отправлен',
      copyFailed: 'Не удалось скопировать ссылку',
      genericError: 'Произошла ошибка',
      firstAnswer: 'Напишите первый ответ!',
      confirmDelete: 'Удалить этот ответ?',
      confirmQuestionDelete: 'Удалить этот вопрос? Это действие нельзя отменить.',
    },
    insights: {
      liveRoom: 'Сейчас онлайн',
      connections: '{{count}} подключений',
      topMentors: 'Самые активные участники',
      community: 'Сообщество',
      topUsers: 'Самые активные участники',
      activeUser: 'Активный участник',
      userBadges: ['Самый активный автор ответов', 'Много помогал другим', 'Полезные решения', 'Активен в обсуждениях', 'Участник недели'],
      weeklyChallenge: 'Задание недели',
      reactionMarathon: 'Марафон реакций',
      challengeText: 'Каждый день записывайте одну реакцию с полным механизмом и обсуждайте ее с сообществом.',
      view: 'Посмотреть',
    },
    home: {
      chemistryChat: 'Форум по химии',
      home: 'Главная',
      features: 'Возможности',
      about: 'О нас',
      community: 'Сообщество',
      eyebrow: 'Beyond curriculum · живая помощь по химии',
      title1: 'Самый живой',
      title2: 'форум по химии',
      title3: 'для нового старта',
      intro: 'ChOUZ Team объединяет вопросы, ответы наставников, формулы и энергию сообщества. Сейчас в центре форум, затем появятся уроки и практика.',
      openChat: 'Открыть форум',
      questionFlow: 'Лента вопросов',
      chemistrySections: 'Раздела химии',
      lessonsMode: 'Режим уроков',
      mentorAnswered: 'Наставник ответил',
      newDiscussions: '{{count}} новых обсуждений',
      writeQuestion: 'Написать вопрос…',
      featuresHeading: 'Форум уже работает, а структура готова для следующих разделов.',
      aboutHeading: 'ChOUZ Team — сообщество, которое вместе разбирается в химии.',
      aboutText: 'Наша цель — не сухой ответ, а понятный путь. Каждый вопрос сохраняется вместе с формулами, попытками и обсуждением, чтобы он помогал и следующим ученикам.',
      roadmap: 'План развития ChOUZ Team',
      now: 'Сейчас',
      next: 'Далее',
      nowItems: 'Форум, вопросы, ответы, рейтинг',
      nextItems: 'Уроки, практические задания, мини-олимпиады',
      later: 'Позже',
      laterItems: 'Комнаты наставников, группы, карта прогресса',
      join: 'Присоединиться к сообществу',
      joinText: 'Задавайте вопросы, публикуйте решения и изучайте химию вместе.',
      communityHeading: 'Откройте первое обсуждение. Всё остальное продолжится внутри.',
      communityChat: 'Форум сообщества',
      communitySections: 'Разделы сообщества',
      communityItems: ['Органическая химия', 'Подготовка к DTM', 'Олимпиадный спринт', 'Механизмы реакций', 'Аналитические задачи', 'Ответы наставников'],
      reactionSearch: 'Реакция H2SO4 + CuO…',
      grignardQuestion: 'Как работает механизм Гриньяра?',
      mentorMessage: 'Происходит нуклеофильная атака на карбонильный углерод.',
      learnerMessage: 'Значит, образуется первичный спирт?',
      pressureQuestion: 'Ле Шателье: что будет при повышении давления?',
      feature1Title: 'Форум на первом месте',
      feature1Text: 'Вопрос, решение, формула и изображение находятся в одной живой ленте.',
      feature2Title: 'Формулы уже готовы',
      feature2Text: 'Реакции, LaTeX, индексы и пошаговые решения выглядят аккуратно.',
      feature3Title: 'Наставники и рейтинг',
      feature3Text: 'Полезные ответы поднимаются выше, а активные участники заметны в сообществе.',
      feature4Title: 'Место для уроков',
      feature4Text: 'Структура готова для олимпиад, мини-курсов, тестов и практики.',
    },
    profile: {
      notFound: 'Пользователь не найден',
      since: 'с {{date}}',
      points: 'Баллы',
      questions: 'Вопросы',
      answers: 'Ответы',
      accepted: 'Принято',
      questionsTab: 'Вопросы ({{count}})',
      answersTab: 'Ответы ({{count}})',
      noQuestions: 'Вопросов пока нет',
      noAnswers: 'Ответов пока нет',
      answerCount: '{{count}} ответов',
      pointCount: '{{count}} баллов',
      viewCount: '{{count}} просмотров',
      acceptedBadge: 'Принят',
      publicProfile: 'Публичный профиль',
      editProfile: 'Редактировать профиль',
      displayName: 'Отображаемое имя',
      username: 'Username',
      role: 'Роль',
      headline: 'Короткий заголовок',
      bio: 'Био',
      about: 'О себе',
      noBio: 'Био пока не заполнено.',
      location: 'Местоположение',
      website: 'Сайт',
      studyGoal: 'Учебная цель',
      profileDetails: 'Данные профиля',
      noDetails: 'Дополнительных данных пока нет',
      interestsLabel: 'Интересы',
      interestsHint: 'органическая химия, DTM, титрование',
      noInterests: 'Интересы пока не добавлены.',
      avatarPhoto: 'Фото профиля',
      coverPhoto: 'Обложка',
      coverSamples: 'Готовые фоны',
      avatarSamples: 'Готовые аватары',
      coverPresetLab: 'Лаборатория',
      coverPresetOrbit: 'Орбита',
      coverPresetNotebook: 'Тетрадь',
      coverPresetCrystal: 'Кристалл',
      coverPresetReaction: 'Реакция',
      avatarPresetChemist: 'Химик',
      avatarPresetNeon: 'Неон',
      avatarPresetMint: 'Мягкий',
      avatarPresetViolet: 'Виолет',
      avatarPresetGraphite: 'Графит',
      avatarPresetSolar: 'Солнце',
      removePhoto: 'Удалить',
      saveChanges: 'Сохранить изменения',
      saving: 'Сохранение…',
      profileUpdated: 'Профиль обновлен',
      editError: 'Не удалось сохранить профиль. Попробуйте снова.',
      imageError: 'Не удалось загрузить изображение.',
      messageUser: 'Написать',
      contribution: 'Активность',
      solvedRate: 'Доля принятых',
      completed: 'Принятые ответы',
      tiers: { diamond: 'АЛМАЗ', platinum: 'ПЛАТИНА', gold: 'ЗОЛОТО', silver: 'СЕРЕБРО', learner: 'УЧЕНИК' },
    },
    ranking: {
      period: 'Период',
      periods: { week: 'Эта неделя', month: 'Этот месяц', quarter: 'Этот квартал', year: 'Год', all: 'За всё время' },
      rules: 'Как работает рейтинг',
      acceptedRule: 'Ответ принят',
      upvoteRule: 'Голос за',
      olympiadRule: 'Победа на олимпиаде',
      mentorRule: 'Подтверждение наставника',
      coefficient: 'коэффициент',
      leaders: 'Лидеры недели',
      mostActive: 'Самые активные',
      chemists: 'в рейтинге химиков',
      intro: 'Рейтинг строится по баллам профиля пользователя. Сейчас автоматические баллы в основном начисляются за принятые ответы; голоса влияют на порядок вопросов и ответов.',
      ruleRows: [
        { label: 'Принятый ответ', value: '+50 баллов', detail: 'Если автор вопроса или модератор принимает ответ, автор ответа получает баллы профиля.' },
        { label: 'Голоса за ответы', value: 'Рейтинг ответа', detail: 'Upvote/downvote меняет score самого ответа и поднимает более полезные ответы выше.' },
        { label: 'Голоса за вопросы', value: 'Рейтинг вопроса', detail: 'Голоса за вопрос меняют score вопроса, но не добавляются к баллам профиля автора.' },
        { label: 'Фильтры периода', value: 'Журнал баллов', detail: 'Неделя, месяц, квартал и год считаются по записям начисления баллов за этот период.' },
      ],
      rulesNote: 'Рейтинг за всё время берётся из общего балла профиля. Демо-баллы или изменения администратора тоже могут отображаться в общем балле.',
      user: 'Пользователь',
      points: 'Баллы',
      accepted: 'Принято',
      change: 'Изм.',
    },
    communityPage: {
      communities: 'Сообщества',
      purpose: 'Цель',
      usefulPages: 'Полезные страницы о химии',
      purposeText: 'Здесь собраны сайты сообществ, материалы и официальные каналы, полезные пользователям ChOUZ Team.',
      ourCommunity: 'Наше сообщество',
      title: 'Химическое сообщество',
      intro: 'Полезные сообщества для изучающих химию, их сайты, библиотеки и сведения о командах собраны здесь.',
      openUac: 'Открыть сайт UAC',
      library: 'Библиотека',
      oneSite: 'Пока 1 сайт',
      websites: 'Сайты сообществ',
      uacTeam: 'Команда UAC',
      membersInfo: 'Участники и информация',
      contact: 'Контакты',
      source: 'Источник',
      officialPage: 'Официальная страница',
      sourceText: 'Информация о команде взята со страницы UAC. Позже другие сайты сообществ будут добавлены в том же формате.',
      website: 'сайт',
      teamMembers: 'участников команды',
      socialChannels: 'социальных каналов',
      openSite: 'Открыть сайт',
      websiteLabel: 'Сайт сообщества',
      teamLabel: 'Команда {{name}}',
    },
    news: {
      title: 'Мировые новости химии',
      intro: 'Последние открытия в химии со всего мира от ScienceDaily',
      error: 'Не удалось загрузить новости. Попробуйте снова.',
    },
    tools: {
      eyebrow: 'Инструменты химии',
      title: 'Расчётный центр',
      intro: 'Уравнивайте реакции, рассчитывайте состав вещества и пошагово находите количество продукта из реагента.',
      tabsLabel: 'Инструменты химических расчётов',
      toolCount: '3 инструмента',
      workspace: 'Единое рабочее пространство',
      workspaceText: 'Коэффициенты уравнения напрямую передаются в стехиометрический расчёт. Все результаты вычисляются в браузере.',
      checks: ['Простые формулы и скобки', 'Атомные массы 94 элементов', 'Граммы, моли и частицы', 'Ответ с этапами решения'],
      rule: 'Правило расчёта',
      theoretical: 'Теоретический результат',
      theoreticalText: 'Инструмент стехиометрии принимает чистоту реагента и выход реакции за 100%. Лабораторный результат может отличаться.',
      balance: 'Балансировка',
      balanceCaption: 'Баланс атомов',
      molarMass: 'Молярная масса',
      massCaption: 'Состав и конверсия',
      stoichiometry: 'Стехиометрия',
      stoichCaption: 'От реагента к продукту',
      calculationFailed: 'Не удалось рассчитать',
      amountUnit: 'Единица количества',
      reactionEquation: 'Уравнение реакции',
      balancedEquation: 'Сбалансированное уравнение',
      reactants: 'Реагенты',
      products: 'Продукты',
      reactionType: 'Тип реакции',
      element: 'Элемент',
      left: 'Слева',
      right: 'Справа',
      status: 'Статус',
      whatHappened: 'Что произошло?',
      copyAsQuestion: 'Скопировать как вопрос для форума',
      conversion: 'Преобразование количества',
      amount: 'Количество',
      mass: 'Масса',
      substanceAmount: 'Количество вещества',
      particles: 'Частицы',
      massComposition: 'Массовый состав',
      count: 'Число',
      atomicMass: 'Атомная масса',
      share: 'Доля',
      automaticBalance: 'Автоматический баланс',
      initialAmount: 'Исходное количество',
      yieldNote: 'Предполагается 100% выход реакции.',
      theoreticalResult: 'Теоретический результат',
      productAmount: 'Количество продукта',
      coefficientRatio: 'Отношение коэффициентов',
      solutionSteps: 'Этапы решения',
      balanced: 'Равны',
      errorStatus: 'Ошибка',
      substanceFormula: 'Формула вещества',
      atomTotal: 'Всего {{count}} атомов в одной молекуле.',
      reactionToBalance: 'Реакция для балансировки',
      givenSubstance: 'Исходное вещество',
      targetSubstance: 'Искомое вещество',
      reactant: 'реагент',
      product: 'продукт',
      ratioStep: 'По отношению коэффициентов × {{ratio}}',
      molarMassStep: 'Молярная масса {{formula}}:',
    },
    admin: {
      loginRequired: 'Необходимо войти',
      noPermission: 'Нет прав модератора',
      deniedText: 'Эта страница доступна только администраторам и модераторам.',
      firstAdminTitle: 'Создать первого администратора',
      firstAdminText: 'Если администратора ещё нет, сделайте этот аккаунт первым администратором. Если администратор уже есть, он должен назначить вас.',
      firstAdminAction: 'Сделать меня первым админом',
      firstAdminWorking: 'Проверяем…',
      firstAdminDone: 'Права администратора выданы. Страница обновляется…',
      firstAdminError: 'Не удалось назначить администратора',
      home: 'На главную',
      adminCenter: 'Центр управления ChOUZ Team',
      moderatorCenter: 'Центр управления модератора',
      today: '+{{count}} сегодня',
      users: 'Пользователи',
      topics: 'Темы',
      answers: 'Ответы',
      moderators: 'Модераторы',
      banned: 'Заблокированы',
      overview: 'Обзор',
      content: 'Контент',
      permissions: 'Права',
      announcement: 'Объявление',
      recentTopics: 'Последние темы',
      recentAnswers: 'Последние ответы',
      allUsers: 'Все пользователи ({{count}})',
      searchUsers: 'Поиск по имени, email или username…',
      user: 'Пользователь',
      points: 'Баллы',
      status: 'Статус',
      actions: 'Действия',
      roleRights: 'Права ролей',
      adminAssigns: 'Администратор настраивает права модераторов',
      section: 'Раздел',
      right: 'Право',
      allowed: 'Да',
      denied: 'Нет',
      turnOnRight: 'Разрешить модератору',
      turnOffRight: 'Убрать у модератора',
      recent50: 'Последние 50',
      title: 'Заголовок',
      author: 'Автор',
      answer: 'Ответы',
      sendAnnouncement: 'Отправить объявление всем пользователям',
      announcementHelp: 'Объявление появится в уведомлениях всех зарегистрированных пользователей.',
      announcementPlaceholder: 'Введите текст объявления… (до 500 символов)',
      sending: 'Отправка…',
      send: 'Отправить',
    },
  },
  en: {
    common: {
      back: 'Back',
      close: 'Close',
      loading: 'Loading…',
      retry: 'Try again',
      save: 'Save',
      saved: 'Saved',
      send: 'Send',
      open: 'Open',
      solved: 'Solved',
      copied: 'Copied',
      optional: 'optional',
      now: 'Now',
      today: 'Today',
      yesterday: 'Yesterday',
      language: 'Language',
      soon: 'soon',
      live: 'live',
    },
    time: {
      now: 'Now',
      minutesAgo: '{{count}} min ago',
      hoursAgo: '{{count}} hr ago',
      daysAgo: '{{count}} days ago',
    },
    nav: {
      main: 'Main sections',
      chat: 'Forum',
      messages: 'Messages',
      olympiads: 'Olympiads',
      community: 'Community',
      ranking: 'Ranking',
      tools: 'Tools',
      news: 'News',
      profile: 'Profile',
      myProfile: 'My profile',
      savedQuestions: 'Saved questions',
      login: 'Log in',
      logout: 'Log out',
      adminRole: 'Admin',
      moderatorRole: 'Moderator',
      adminPanel: 'Admin panel',
      moderatorPanel: 'Moderator panel',
      mobile: 'Mobile navigation',
    },
    header: {
      tagline: 'Beyond Curriculum · Chemistry',
      search: 'Search questions, tags, or reactions',
      theme: 'Change theme',
      notifications: 'Notifications',
      allRead: 'all read',
      newCount: '{{count}} new',
      noNotifications: 'No notifications yet',
      askQuestion: 'Ask a question',
    },
    auth: {
      welcome: 'Welcome',
      createAccount: 'Create account',
      login: 'Log in',
      register: 'Sign up',
      fullName: 'Full name',
      email: 'Email',
      username: 'Username',
      password: 'Password',
      minPassword: 'at least 6 characters',
      noAccount: "Don't have an account?",
      haveAccount: 'Already have an account?',
      registerAction: 'Sign up',
      loginAction: 'Log in',
      registerError: 'Registration failed',
      loginError: 'Login failed',
    },
    forum: {
      categories: 'Sections',
      all: 'All',
      organic: 'Organic chemistry',
      inorganic: 'Inorganic',
      physical: 'Physical',
      analytical: 'Analytical',
      recent: 'Recent',
      hot: 'Hot',
      unanswered: 'Unanswered',
      saved: 'Saved',
      feed: 'Question feed',
      compact: 'Compact',
      spacious: 'Spacious',
      masteryLevel: 'Mastery level',
      upvotes: 'Upvotes',
      answers: 'Answers',
      shared: 'Shared',
      dailySprint: 'Daily sprint',
      sprintText: 'Leave a helpful comment in three chemistry discussions today.',
      trendingTags: 'Trending tags',
      demoMode: 'Demo mode',
      demoText: 'The live API is responding slowly, so sample questions are shown.',
      noResults: 'No results found',
      noResultsHint: 'Try another word or subject.',
      noSaved: 'No saved questions yet',
      noSavedHint: 'Use the bookmark on any question to keep it here.',
      signInForSaved: 'Log in to see saved questions',
      signInForSavedHint: 'Saved questions are kept with your account.',
      pinned: 'Pinned topic',
      views: 'Views',
      copyLink: 'Copy question link',
      linkCopied: 'Link copied',
      upvote: 'Upvote',
      downvote: 'Downvote',
      voteUp: 'Upvote',
      voteDown: 'Downvote',
      voteRemoved: 'Vote removed',
      voteSaved: 'Vote saved',
      voteFailed: 'Could not save your vote. Try again',
      demoVote: 'Votes are not saved in demo mode',
      savedUpdated: 'Saved topics updated',
      answerSent: 'Answer sent',
      topicCreated: 'Topic created',
      topicCreateError: 'Could not create the topic. Try again.',
      follow: 'Follow',
      discussion: 'Discussion',
      usefulFirst: 'Most helpful first',
      answerCount: '{{count}} answers',
      noAnswers: 'No answers yet',
      noAnswersHint: 'The first clear answer will start this discussion.',
      writeAnswer: 'Write an answer',
      answerPlaceholder: 'Write a hint, formula, or full solution…',
      sendAnswer: 'Send answer',
      sending: 'Sending…',
    },
    messages: {
      eyebrow: 'Direct chat',
      title: 'Messages',
      people: 'Users',
      conversations: 'Conversations',
      searchUsers: 'Search users',
      noConversations: 'No conversations yet',
      noUsers: 'No users found',
      noMessages: 'No messages yet',
      startChat: 'Message',
      youPrefix: 'You: ',
      newMessage: 'New',
      selectConversation: 'Choose a conversation',
      selectConversationText: 'Open an existing conversation on the left or start a new chat with a user.',
      emptyThread: 'Send the first message',
      emptyThreadText: 'This conversation has not started yet.',
      messagePlaceholder: 'Write a message…',
      sendMessage: 'Send',
      sending: 'Sending…',
      loginTitle: 'Log in to use messages',
      loginText: 'Log in or create an account to talk privately with other users.',
      loginAction: 'Log in',
      loadError: 'Could not load messages. Try again.',
      sendError: 'Could not send the message. Try again.',
      startError: 'Could not open the conversation. Try again.',
    },
    composer: {
      newTopic: 'New topic',
      newQuestion: 'New chemistry question',
      write: 'Write',
      preview: 'Preview',
      title: 'Title',
      titlePlaceholder: 'For example: how does sulfuric acid react with CuO?',
      chemistry: 'Chemistry',
      formula: 'Formula',
      fraction: 'Fraction',
      reaction: 'Reaction',
      reversible: 'Reversible',
      charge: 'Charge',
      state: 'State',
      precipitate: 'Precipitate',
      formatting: 'Markdown formatting',
      mathKeyboard: 'Keyboard',
      formulaGroup: 'Formula section',
      bold: 'Bold',
      italic: 'Italic',
      list: 'List',
      quote: 'Quote',
      code: 'Code',
      link: 'Link',
      questionText: 'Question text',
      questionPlaceholder: 'Write your question — formulas can be inserted directly.',
      category: 'Section',
      tags: 'Tags',
      tagsHint: 'separate with commas',
      emptyPreview: 'Your question preview will appear here.',
      emptyTitle: 'No title yet',
      previewLabel: 'Preview',
      image: 'Image',
      removeImage: 'Remove image {{name}}',
      cancel: 'Cancel',
      creating: 'Saving…',
      create: 'Create topic',
    },
    question: {
      forum: 'Forum',
      notFound: 'Question not found',
      asked: 'Asked by',
      createdAt: 'Created at',
      editQuestion: 'Edit question',
      editQuestionTitle: 'Update question',
      saveQuestion: 'Save changes',
      savingQuestion: 'Saving…',
      questionUpdated: 'Question updated',
      questionUpdateError: 'Could not update the question',
      activity: 'Activity',
      status: 'Status',
      about: 'About this question',
      tags: 'Tags',
      acceptAnswer: 'Accept this answer',
      accepted: 'Accepted',
      answerAccepted: 'Answer accepted',
      markSolved: 'Solved',
      markOpen: 'Reopen',
      signInToAnswer: 'Log in to answer',
      loginOrRegister: 'Log in / Sign up',
      helpful: 'Helpful',
      unhelpful: 'Unhelpful',
      correct: 'Correct',
      incorrect: 'Incorrect',
      delete: 'Delete',
      deleteQuestion: 'Delete question',
      answerDeleted: 'Answer deleted',
      questionDeleted: 'Question deleted',
      answerMarked: 'Answer marked',
      questionSolved: 'Question solved',
      questionOpened: 'Question reopened',
      questionLinkCopied: 'Question link copied',
      answerLinkCopied: 'Answer link copied',
      copyAnswerLink: 'Copy answer link',
      reply: 'Reply',
      replyPlaceholder: 'Write a reply to this answer…',
      sendReply: 'Send',
      sendingReply: 'Sending…',
      replySent: 'Reply sent',
      copyFailed: 'Could not copy the link',
      genericError: 'Something went wrong',
      firstAnswer: 'Write the first answer!',
      confirmDelete: 'Delete this answer?',
      confirmQuestionDelete: 'Delete this question? This cannot be undone.',
    },
    insights: {
      liveRoom: 'Live room',
      connections: '{{count}} connections',
      topMentors: 'Most active users',
      community: 'Community',
      topUsers: 'Most active users',
      activeUser: 'Active member',
      userBadges: ['Most active answerer', 'Helped many people', 'Helpful solutions', 'Active in discussions', 'Member of the week'],
      weeklyChallenge: 'Weekly challenge',
      reactionMarathon: 'Reaction marathon',
      challengeText: 'Write one chemistry reaction with its full mechanism every day and discuss it with the community.',
      view: 'View',
    },
    home: {
      chemistryChat: 'Chemistry forum',
      home: 'Home',
      features: 'Features',
      about: 'About us',
      community: 'Community',
      eyebrow: 'Beyond curriculum · live chemistry help',
      title1: 'The liveliest',
      title2: 'chemistry forum',
      title3: 'for a fresh start',
      intro: 'ChOUZ Team brings questions, mentor answers, formulas, and community energy together. Forum is the main stage now, with lessons and practice coming next.',
      openChat: 'Open forum',
      questionFlow: 'Question feed',
      chemistrySections: 'Chemistry sections',
      lessonsMode: 'Lessons mode',
      mentorAnswered: 'A mentor replied',
      newDiscussions: '{{count}} new discussions',
      writeQuestion: 'Write a question…',
      featuresHeading: 'Forum works today, and the structure is ready for what comes next.',
      aboutHeading: 'ChOUZ Team is a community that understands chemistry together.',
      aboutText: 'The goal is simple: a clear path, not a dry answer. Every question is saved with formulas, attempts, and discussion so future learners can benefit too.',
      roadmap: 'ChOUZ Team roadmap',
      now: 'Now',
      next: 'Next',
      nowItems: 'Forum, questions, answers, ranking',
      nextItems: 'Lessons, practice sets, mini olympiads',
      later: 'Later',
      laterItems: 'Mentor rooms, cohorts, progress maps',
      join: 'Join the community',
      joinText: 'Ask questions, share solutions, and understand chemistry together.',
      communityHeading: 'Open the first discussion. Everything else continues inside.',
      communityChat: 'Community forum',
      communitySections: 'Community sections',
      communityItems: ['Organic chemistry', 'DTM preparation', 'Olympiad sprint', 'Reaction mechanisms', 'Analytical problems', 'Mentor answers'],
      reactionSearch: 'H2SO4 + CuO reaction…',
      grignardQuestion: 'How does the Grignard mechanism work?',
      mentorMessage: 'A nucleophilic attack occurs at the carbonyl carbon.',
      learnerMessage: 'So does it form a primary alcohol?',
      pressureQuestion: 'Le Chatelier: what happens when pressure rises?',
      feature1Title: 'Forum comes first',
      feature1Text: 'Questions, solutions, formulas, and images live in one active feed.',
      feature2Title: 'Chemistry formulas are ready',
      feature2Text: 'Reactions, LaTeX, subscripts, and step-by-step solutions render cleanly.',
      feature3Title: 'Mentors and rankings',
      feature3Text: 'Helpful answers rise while active contributors stand out in the community.',
      feature4Title: 'Room for lessons',
      feature4Text: 'The structure is ready for olympiads, mini-courses, tests, and practice.',
    },
    profile: {
      notFound: 'User not found',
      since: 'since {{date}}',
      points: 'Points',
      questions: 'Questions',
      answers: 'Answers',
      accepted: 'Accepted',
      questionsTab: 'Questions ({{count}})',
      answersTab: 'Answers ({{count}})',
      noQuestions: 'No questions yet',
      noAnswers: 'No answers yet',
      answerCount: '{{count}} answers',
      pointCount: '{{count}} points',
      viewCount: '{{count}} views',
      acceptedBadge: 'Accepted',
      publicProfile: 'Public profile',
      editProfile: 'Edit profile',
      displayName: 'Display name',
      username: 'Username',
      role: 'Role',
      headline: 'Short headline',
      bio: 'Bio',
      about: 'About',
      noBio: 'No bio has been added yet.',
      location: 'Location',
      website: 'Website',
      studyGoal: 'Study goal',
      profileDetails: 'Profile details',
      noDetails: 'No extra details yet',
      interestsLabel: 'Interests',
      interestsHint: 'organic chemistry, DTM, titration',
      noInterests: 'No interests added yet.',
      avatarPhoto: 'Profile photo',
      coverPhoto: 'Cover photo',
      coverSamples: 'Ready backgrounds',
      avatarSamples: 'Ready avatars',
      coverPresetLab: 'Laboratory',
      coverPresetOrbit: 'Orbit',
      coverPresetNotebook: 'Notebook',
      coverPresetCrystal: 'Crystal',
      coverPresetReaction: 'Reaction',
      avatarPresetChemist: 'Chemist',
      avatarPresetNeon: 'Neon',
      avatarPresetMint: 'Soft',
      avatarPresetViolet: 'Violet',
      avatarPresetGraphite: 'Graphite',
      avatarPresetSolar: 'Solar',
      removePhoto: 'Remove',
      saveChanges: 'Save changes',
      saving: 'Saving…',
      profileUpdated: 'Profile updated',
      editError: 'Could not save the profile. Try again.',
      imageError: 'Could not load the image.',
      messageUser: 'Message',
      contribution: 'Contribution',
      solvedRate: 'Accepted rate',
      completed: 'Accepted answers',
      tiers: { diamond: 'DIAMOND', platinum: 'PLATINUM', gold: 'GOLD', silver: 'SILVER', learner: 'LEARNER' },
    },
    ranking: {
      period: 'Period',
      periods: { week: 'This week', month: 'This month', quarter: 'This quarter', year: 'Yearly', all: 'All time' },
      rules: 'How ranking works',
      acceptedRule: 'Accepted answer',
      upvoteRule: 'Upvote',
      olympiadRule: 'Olympiad win',
      mentorRule: 'Mentor approval',
      coefficient: 'multiplier',
      leaders: 'Weekly leaders',
      mostActive: 'Most active',
      chemists: 'chemists ranking',
      intro: 'Ranking is based on a user’s profile points. Right now automatic points mainly come from accepted answers; votes affect the ordering of questions and answers.',
      ruleRows: [
        { label: 'Accepted answer', value: '+50 points', detail: 'When the question owner or a moderator accepts an answer, the answer author receives profile points.' },
        { label: 'Answer votes', value: 'Answer score', detail: 'Upvotes and downvotes change the answer’s own score and help useful answers appear higher.' },
        { label: 'Question votes', value: 'Question score', detail: 'Question votes change the question score, but they do not add profile points to the author.' },
        { label: 'Period filters', value: 'Score log', detail: 'Week, month, quarter, and year rankings are calculated from score-log entries in that period.' },
      ],
      rulesNote: 'All-time ranking uses the user’s total profile score. Demo points or admin score changes can also appear in the total score.',
      user: 'User',
      points: 'Points',
      accepted: 'Accepted',
      change: 'Change',
    },
    communityPage: {
      communities: 'Communities',
      purpose: 'Purpose',
      usefulPages: 'Useful chemistry pages',
      purposeText: 'This section gathers community sites, materials, and official channels useful to ChOUZ Team members.',
      ourCommunity: 'Our community',
      title: 'Chemistry community',
      intro: 'Helpful communities for chemistry learners, their sites, libraries, and team information are collected here.',
      openUac: 'Open the UAC site',
      library: 'Library',
      oneSite: '1 site for now',
      websites: 'Community websites',
      uacTeam: 'UAC team',
      membersInfo: 'Members and information',
      contact: 'Contact',
      source: 'Source',
      officialPage: 'Official page',
      sourceText: 'Team information comes from the UAC page. More community sites will be added later in the same format.',
      website: 'website',
      teamMembers: 'team members',
      socialChannels: 'social channels',
      openSite: 'Open site',
      websiteLabel: 'Community website',
      teamLabel: '{{name}} team',
    },
    news: {
      title: 'World chemistry news',
      intro: 'The latest chemistry discoveries from around the world via ScienceDaily',
      error: 'Could not load the news. Try again.',
    },
    tools: {
      eyebrow: 'Chemistry tools',
      title: 'Calculation center',
      intro: 'Balance equations, calculate compound composition, and find product amounts from reagents step by step.',
      tabsLabel: 'Chemistry calculation tools',
      toolCount: '3 tools',
      workspace: 'One chemistry workspace',
      workspaceText: 'Equation coefficients flow directly into stoichiometry calculations. Results are computed in your browser.',
      checks: ['Simple formulas and parentheses', 'Atomic masses for 94 elements', 'Grams, moles, and particles', 'Answers with solution steps'],
      rule: 'Calculation rule',
      theoretical: 'Theoretical result',
      theoreticalText: 'The stoichiometry tool assumes 100% reagent purity and reaction yield. Laboratory results may differ.',
      balance: 'Balance',
      balanceCaption: 'Atom balance',
      molarMass: 'Molar mass',
      massCaption: 'Composition and conversion',
      stoichiometry: 'Stoichiometry',
      stoichCaption: 'Reactant to product',
      calculationFailed: 'Could not calculate',
      amountUnit: 'Amount unit',
      reactionEquation: 'Reaction equation',
      balancedEquation: 'Balanced equation',
      reactants: 'Reactants',
      products: 'Products',
      reactionType: 'Reaction type',
      element: 'Element',
      left: 'Left',
      right: 'Right',
      status: 'Status',
      whatHappened: 'What happened?',
      copyAsQuestion: 'Copy as a forum question',
      conversion: 'Convert amount',
      amount: 'Amount',
      mass: 'Mass',
      substanceAmount: 'Amount of substance',
      particles: 'Particles',
      massComposition: 'Mass composition',
      count: 'Count',
      atomicMass: 'Atomic mass',
      share: 'Share',
      automaticBalance: 'Automatic balance',
      initialAmount: 'Starting amount',
      yieldNote: 'A 100% reaction yield is assumed.',
      theoreticalResult: 'Theoretical result',
      productAmount: 'Product amount',
      coefficientRatio: 'Coefficient ratio',
      solutionSteps: 'Solution steps',
      balanced: 'Balanced',
      errorStatus: 'Error',
      substanceFormula: 'Compound formula',
      atomTotal: 'A single molecule contains {{count}} atoms.',
      reactionToBalance: 'Reaction to balance',
      givenSubstance: 'Given substance',
      targetSubstance: 'Target substance',
      reactant: 'reactant',
      product: 'product',
      ratioStep: 'Using the equation ratio × {{ratio}}',
      molarMassStep: 'Molar mass of {{formula}}:',
    },
    admin: {
      loginRequired: 'Login required',
      noPermission: 'Moderator access required',
      deniedText: 'Only administrators and moderators can access this page.',
      firstAdminTitle: 'Create the first admin',
      firstAdminText: 'If no admin exists yet, make this account the first admin. If an admin already exists, that admin must assign you.',
      firstAdminAction: 'Make me first admin',
      firstAdminWorking: 'Checking…',
      firstAdminDone: 'Admin access granted. Refreshing…',
      firstAdminError: 'Could not assign admin access',
      home: 'Home',
      adminCenter: 'ChOUZ Team administration center',
      moderatorCenter: 'Moderator control center',
      today: '+{{count}} today',
      users: 'Users',
      topics: 'Topics',
      answers: 'Answers',
      moderators: 'Moderators',
      banned: 'Banned',
      overview: 'Overview',
      content: 'Content',
      permissions: 'Permissions',
      announcement: 'Announcement',
      recentTopics: 'Recent topics',
      recentAnswers: 'Recent answers',
      allUsers: 'All users ({{count}})',
      searchUsers: 'Search by name, email, or username…',
      user: 'User',
      points: 'Points',
      status: 'Status',
      actions: 'Actions',
      roleRights: 'Role permissions',
      adminAssigns: 'Admins can adjust moderator rights',
      section: 'Section',
      right: 'Permission',
      allowed: 'Yes',
      denied: 'No',
      turnOnRight: 'Allow for moderator',
      turnOffRight: 'Remove from moderator',
      recent50: 'Latest 50',
      title: 'Title',
      author: 'Author',
      answer: 'Answers',
      sendAnnouncement: 'Send an announcement to all users',
      announcementHelp: 'The announcement will appear in every registered user’s notifications.',
      announcementPlaceholder: 'Enter announcement text… (up to 500 characters)',
      sending: 'Sending…',
      send: 'Send',
    },
  },
};

const LanguageContext = createContext(null);

function resolvePath(source, path) {
  return path.split('.').reduce((value, key) => value?.[key], source);
}

function interpolate(value, variables) {
  return Object.entries(variables).reduce(
    (text, [key, replacement]) => text.replaceAll(`{{${key}}}`, String(replacement)),
    value
  );
}

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    const stored = localStorage.getItem(STORAGE_KEY);
    return LANGUAGES.some((item) => item.code === stored) ? stored : DEFAULT_LANGUAGE;
  });

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = useCallback((nextLanguage) => {
    if (LANGUAGES.some((item) => item.code === nextLanguage)) {
      setLanguageState(nextLanguage);
    }
  }, []);

  const t = useCallback((key, variables = {}) => {
    const translated = resolvePath(translations[language], key);
    const fallback = resolvePath(translations[DEFAULT_LANGUAGE], key);
    const value = translated ?? fallback ?? key;
    return typeof value === 'string' ? interpolate(value, variables) : value;
  }, [language]);

  const value = useMemo(() => ({ language, setLanguage, t }), [language, setLanguage, t]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used inside LanguageProvider');
  return context;
}
